/**
 * server/medicalAi/safety.ts
 *
 * Medical safety layer — mirrors the Python scaffold's safety.py.
 * Responsibilities:
 *   1. Detect emergency / red-flag phrases that must always route to ER
 *   2. Enforce role-based response guardrails (patient vs physician vs staff)
 *   3. Strip any PII / PHI from KB-ingested text before storage
 *   4. Attach a structured safety envelope to every LLM response
 */

// ── Emergency keywords that trigger hard ER referral ──────────────────────────
const ER_PHRASES = [
  "chest pain", "chest tightness", "chest pressure",
  "shortness of breath", "can't breathe", "difficulty breathing",
  "stroke", "face drooping", "arm weakness", "sudden numbness",
  "unresponsive", "unconscious", "not breathing",
  "severe bleeding", "uncontrolled bleeding",
  "anaphylaxis", "throat closing", "throat swelling", "can't swallow",
  "severe allergic reaction",
  "suicidal", "want to kill myself", "thinking about suicide",
  "overdose", "took too many pills",
  "seizure", "convulsions",
  "sudden vision loss", "sudden severe headache", "worst headache of my life",
  "coughing blood", "vomiting blood",
  "severe abdominal pain",
  "high fever in infant", "baby not breathing",
];

// ── Safety check result ───────────────────────────────────────────────────────
export interface SafetyResult {
  safe:           boolean;
  erRequired:     boolean;
  triggeredPhrases: string[];
  recommendation:   string;
  severity:         "none" | "low" | "medium" | "high" | "critical";
}

export function checkMessageSafety(text: string): SafetyResult {
  const lower   = text.toLowerCase();
  const matched = ER_PHRASES.filter(p => lower.includes(p));

  if (matched.length > 0) {
    return {
      safe:             false,
      erRequired:       true,
      triggeredPhrases: matched,
      recommendation:   "CALL 911 IMMEDIATELY or go to the nearest Emergency Room. Do not wait.",
      severity:         "critical",
    };
  }

  return {
    safe:             true,
    erRequired:       false,
    triggeredPhrases: [],
    recommendation:   "",
    severity:         "none",
  };
}

// ── Role-based disclaimer ─────────────────────────────────────────────────────
export type MedicalRole = "patient" | "physician" | "staff";

export function getRoleDisclaimer(role: MedicalRole): string {
  switch (role) {
    case "patient":
      return "This information is for general guidance only and does not replace professional medical advice. Always consult your physician for medical decisions.";
    case "physician":
      return "This response is generated by an AI assistant to support — not replace — clinical judgment. Verify all information against current clinical guidelines.";
    case "staff":
      return "AI-generated summary for operational use. Clinical decisions must be made by a licensed provider.";
  }
}

// ── Role-based system prompt prefix ──────────────────────────────────────────
export function getRoleSystemPrompt(role: MedicalRole): string {
  switch (role) {
    case "patient":
      return `You are a helpful medical assistant at an urgent care clinic. 
Speak clearly and compassionately. Avoid medical jargon unless you define it.
Never diagnose. Provide general health education and help patients understand 
their options. Always recommend consulting a physician for medical decisions.
If you detect any emergency symptoms, immediately direct the patient to call 911.`;

    case "physician":
      return `You are a clinical AI assistant supporting a physician at an urgent care clinic.
Provide concise, evidence-based clinical summaries and decision support.
Use standard medical terminology. Reference clinical guidelines where applicable.
Always note uncertainty and recommend physician judgment for all decisions.`;

    case "staff":
      return `You are an operational assistant for clinic staff.
Help with scheduling, documentation, workflows, and general clinic processes.
Do not provide clinical diagnoses or treatment recommendations.
Route clinical questions to the appropriate physician.`;
  }
}

// ── PHI scrubber for knowledge ingestion ─────────────────────────────────────
// Removes common PHI patterns before storing knowledge base documents.
// This is a best-effort layer — full de-identification requires dedicated tooling.
const PHI_PATTERNS: Array<{ pattern: RegExp; replacement: string }> = [
  { pattern: /\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b/g,          replacement: "[PHONE]" },
  { pattern: /\b[A-Z]{2}\d{6,}\b/g,                           replacement: "[MRN]" },
  { pattern: /\b\d{3}-\d{2}-\d{4}\b/g,                        replacement: "[SSN]" },
  { pattern: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z]{2,}\b/gi, replacement: "[EMAIL]" },
  { pattern: /\b\d{1,2}\/\d{1,2}\/\d{2,4}\b/g,               replacement: "[DATE]" },
  { pattern: /\b(DOB|Date of Birth)[:\s]+[^\n,]+/gi,           replacement: "[DOB]" },
  { pattern: /\b(patient name|name)[:\s]+[A-Z][a-z]+\s+[A-Z][a-z]+/gi, replacement: "[NAME]" },
];

export function scrubPHI(text: string): string {
  let scrubbed = text;
  for (const { pattern, replacement } of PHI_PATTERNS) {
    scrubbed = scrubbed.replace(pattern, replacement);
  }
  return scrubbed;
}

// ── Structured safety envelope ────────────────────────────────────────────────
export interface SafetyEnvelope {
  safetyCleared:    boolean;
  erRequired:       boolean;
  disclaimer:       string;
  severity:         SafetyResult["severity"];
  triggeredPhrases: string[];
}

export function buildSafetyEnvelope(
  text:   string,
  role:   MedicalRole,
): SafetyEnvelope {
  const safety     = checkMessageSafety(text);
  const disclaimer = getRoleDisclaimer(role);
  return {
    safetyCleared:    safety.safe,
    erRequired:       safety.erRequired,
    disclaimer,
    severity:         safety.severity,
    triggeredPhrases: safety.triggeredPhrases,
  };
}
