export const ROUTES = {
  OPS: "/ops",
  CLINICAL: "/clinical",
  INTAKE: "/intake",
  SAFETY: "/safety",
  LEARNING: "/learning",
  SYSTEM: "/system",
  SETTINGS: "/settings",
  WORKERS: "/workers",
  CLINIC: "/clinic-health",
  AUTOMATION: "/automation",
  TEMPLATE_STUDIO: "/template-studio",
  ROBOTICS: "/robotics",
  REPLAY_INSPECTOR: "/replay-inspector",
  AUTONOMOUS_BRAIN: "/autonomous-brain",
  MEMORY_EXPLORER: "/memory-explorer",
  ROBOT_ADVANCED: "/robot-advanced",
};
