/**
 * FDA SaMD Intended Use Statement
 *
 * Required for 21 CFR Part 820 Quality System Regulation and FDA's
 * "Software as a Medical Device" (SaMD) Pre-submission framework.
 *
 * Per FDA guidance "Clinical Decision Support Software" (Sept 2022):
 *   - Must explicitly define intended use, user, patient population
 *   - Must state the device class and regulatory pathway
 *   - Must declare human-in-the-loop status
 *   - CDS that is NOT intended to replace clinical judgment is often
 *     exempt from device regulation (21st Century Cures Act, §3060)
 *
 * This file is the authoritative single source of truth for all
 * regulatory filings, 510(k) submissions, and De Novo requests.
 */

export type SaMDClass = "I" | "II" | "III";
export type RegPathway = "510k" | "DeNovo" | "PMA" | "Exempt";

export interface ClinicalScope {
  conditions:       string[];
  patientAges:      string;
  careSetting:      string;
  excludedUses:     string[];
}

export interface RegulatoryProfile {
  deviceClass:        SaMDClass;
  regulatoryPathway:  RegPathway;
  productCode?:       string;
  predicate?:         string;
  imdrf: {
    state:   string;   // IMDRF SaMD state of healthcare situation
    purpose: string;   // IMDRF SaMD intended purpose
    type:    string;   // IMDRF significance
  };
}

export interface IntendedUseStatement {
  productName:        string;
  version:            string;
  lastReviewed:       string;       // ISO date
  description:        string;
  intendedUser:       string;
  intendedPatients:   string;
  clinicalScope:      ClinicalScope;
  humanInLoop:        boolean;
  humanInLoopDetail:  string;
  notIntendedFor:     string[];
  regulatory:         RegulatoryProfile;
  safetyClassification: string;
  contraindications:  string[];
  warnings:           string[];
}

export const intendedUse: IntendedUseStatement = {
  productName: "Auralyn — ENT & Flu Clinical Decision Support Platform",
  version:     "1.0.0",
  lastReviewed: "2026-01-01",

  description:
    "Auralyn is a clinical decision support (CDS) software tool that assists " +
    "licensed healthcare providers in the triage, assessment, and disposition " +
    "planning of patients presenting with ENT (ear, nose, and throat) complaints, " +
    "influenza-like illness, and related upper respiratory conditions. The system " +
    "synthesizes patient-reported symptoms, vital signs, and clinical history to " +
    "generate ranked differential diagnoses, suggested disposition levels, and " +
    "evidence-based management recommendations.",

  intendedUser:
    "Licensed healthcare providers including physicians (MD/DO), nurse " +
    "practitioners (NP/CRNP), physician assistants (PA-C), and registered nurses " +
    "operating under physician supervision in telehealth, urgent care, or primary " +
    "care settings.",

  intendedPatients:
    "Adult and pediatric patients (≥3 months) presenting with acute or subacute " +
    "ENT complaints, influenza-like illness, upper respiratory symptoms, or " +
    "related conditions. Not validated for ICU, ED trauma, or obstetric-primary complaints.",

  clinicalScope: {
    conditions:  [
      "Acute pharyngitis / tonsillopharyngitis",
      "Influenza A/B",
      "COVID-19 (respiratory presentation)",
      "Viral upper respiratory infection (URI)",
      "Acute sinusitis",
      "Otitis media / otitis externa",
      "Epiglottitis (emergency identification only)",
      "Peritonsillar abscess (emergency identification only)",
    ],
    patientAges:  "≥ 3 months to 120 years (age-adjusted scoring applied automatically)",
    careSetting:  "Telehealth, urgent care, primary care, school health, retail clinic",
    excludedUses: [
      "Emergency department as primary triage tool",
      "ICU clinical decision support",
      "Surgical planning",
      "Radiology interpretation",
      "Oncology treatment planning",
      "Mental health diagnosis (screening-only for safety escalation)",
    ],
  },

  humanInLoop: true,
  humanInLoopDetail:
    "All triage recommendations generated by Auralyn are advisory only and must " +
    "be reviewed and approved by a licensed healthcare provider before being " +
    "communicated to or acted upon for any patient. The system is explicitly " +
    "designed as a decision-support aid, not an autonomous diagnostic or " +
    "prescribing system. Auralyn does not initiate treatment, prescribe " +
    "medications, or autonomously order tests without provider authorization.",

  notIntendedFor: [
    "Autonomous diagnosis without provider review",
    "Replacement of physician clinical judgment",
    "Patients in hemodynamic instability as primary triage tool",
    "Mental health primary diagnosis",
    "Use by unlicensed individuals without supervision",
    "Countries where the device is not registered",
  ],

  regulatory: {
    deviceClass:       "II",
    regulatoryPathway: "510k",
    productCode:       "QMG",  // CDS software product code (example)
    predicate:         "K213380", // example 510(k) predicate
    imdrf: {
      state:   "Non-serious condition/situation",
      purpose: "Treat or diagnose",
      type:    "Drive clinical management",
    },
  },

  safetyClassification:
    "Class II Software as a Medical Device (SaMD) per IMDRF framework. " +
    "Subject to 21 CFR Part 820 Quality System Regulation and " +
    "21 CFR Part 11 Electronic Records requirements.",

  contraindications: [
    "Do not use as sole basis for disposition of any patient with acute hemodynamic instability",
    "Do not use for primary mental health crisis management",
    "Do not use in settings without licensed provider oversight",
  ],

  warnings: [
    "Clinical decision support only — does not replace clinical judgment",
    "AI recommendations may be incorrect — always apply clinical reasoning",
    "Ensure patient-reported symptoms are verified by provider examination",
    "System trained on U.S. clinical data — performance in other populations is unvalidated",
  ],
};

/** Machine-readable summary for API and regulatory audit endpoints */
export function getIntendedUseSummary() {
  return {
    productName:       intendedUse.productName,
    version:           intendedUse.version,
    deviceClass:       intendedUse.regulatory.deviceClass,
    pathway:           intendedUse.regulatory.regulatoryPathway,
    humanInLoop:       intendedUse.humanInLoop,
    clinicalConditions: intendedUse.clinicalScope.conditions.length,
    intendedUser:      intendedUse.intendedUser,
    safetyClass:       intendedUse.safetyClassification,
  };
}
