import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import {
  Shield, TrendingUp, Network, Lock, Zap, Star,
  Database, Activity, RefreshCw, FlaskConical,
  ChevronRight, Users, BarChart3, Target,
} from "lucide-react";

/* ── types ─────────────────────────────────────────────────────────────── */
interface MoatScorecard {
  overall: number;
  grade: "A" | "B" | "C" | "D" | "F";
  components: { flywheel: number; rarity: number; network: number; lockin: number };
  flywheel: {
    totalEncounters: number; validatedEncounters: number;
    goldenPromotions: number; velocity24h: number; velocity7d: number; validationRate: number;
  };
  rarity: {
    totalDiagnosesSeen: number; totalEncounters: number;
    rareDxCount: number; ultraRareDxCount: number; rareCoverageRate: number;
  };
  network: {
    activeClinicCount: number; totalNetworkCases: number;
    specialtyBreakdown: Array<{ specialty: string; cases: number; share: number }>;
    networkMultiplier: number;
  };
  lockin: {
    clinicsWithHighCost: number; averageValueScore: number;
    topClinicValueScore: number; totalAccumulatedPatterns: number;
  };
  goldenDataset: { total: number; autoGenerated: number; specialtyCoverage: number };
  generatedAt: string;
}

/* ── helpers ─────────────────────────────────────────────────────────────── */
function gradeColor(g: string) {
  if (g === "A") return "text-green-600 dark:text-green-400";
  if (g === "B") return "text-blue-600 dark:text-blue-400";
  if (g === "C") return "text-yellow-600 dark:text-yellow-400";
  if (g === "D") return "text-orange-600 dark:text-orange-400";
  return "text-red-600 dark:text-red-400";
}

function costBadge(label: string) {
  const m: Record<string, string> = {
    VERY_HIGH: "bg-green-100 text-green-800",
    HIGH:      "bg-blue-100 text-blue-800",
    MODERATE:  "bg-yellow-100 text-yellow-800",
    LOW:       "bg-gray-100 text-gray-700",
  };
  return m[label] ?? "bg-gray-100 text-gray-700";
}

function pct(n: number) { return (n * 100).toFixed(1) + "%"; }

/* ── component ───────────────────────────────────────────────────────────── */
export default function MoatIntelligencePage() {
  const { toast } = useToast();
  const qc = useQueryClient();

  const [simClinic, setSimClinic]     = useState("clinic-nyc-001");
  const [simDiagnosis, setSimDiagnosis] = useState("strep_pharyngitis");
  const [simComplaint, setSimComplaint] = useState("sore throat");
  const [simValidated, setSimValidated] = useState(true);

  const { data: scorecard, isLoading, refetch } = useQuery<MoatScorecard>({
    queryKey: ["/api/moat/scorecard"],
    refetchInterval: 30000,
  });

  const { data: clinicValues } = useQuery<{ clinics: any[]; count: number }>({
    queryKey: ["/api/moat/clinic-values"],
  });

  const simulate = useMutation({
    mutationFn: () => apiRequest("POST", "/api/moat/simulate-encounter", {
      clinicId:   simClinic,
      complaint:  simComplaint,
      diagnosis:  simDiagnosis,
      validated:  simValidated,
    }),
    onSuccess: async (res: any) => {
      const d = await res.json();
      toast({
        title: "Flywheel recorded",
        description: `${d.rarity?.label} · ${d.specialty} · ${d.message}`,
      });
      qc.invalidateQueries({ queryKey: ["/api/moat/scorecard"] });
      qc.invalidateQueries({ queryKey: ["/api/moat/clinic-values"] });
    },
  });

  const s = scorecard;

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-8">

      {/* ── header ───────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between">
        <div>
          <h1
            className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2"
            data-testid="text-moat-title"
          >
            <Shield className="h-6 w-6 text-indigo-600" />
            Moat Intelligence Dashboard
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            Defensibility &amp; Data Network Effect Engine — the compounding advantage that makes Auralyn impossible to copy
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => refetch()}
          data-testid="button-refresh-moat"
        >
          <RefreshCw className="h-4 w-4 mr-1" /> Refresh
        </Button>
      </div>

      {isLoading && (
        <div className="flex items-center gap-2 text-gray-500 animate-pulse" data-testid="status-loading">
          <Activity className="h-4 w-4" /> Computing moat scorecard…
        </div>
      )}

      {s && (
        <>
          {/* ── overall moat score ─────────────────────────────────────── */}
          <div
            className="bg-gradient-to-br from-indigo-50 to-purple-50 dark:from-indigo-900/20 dark:to-purple-900/20 border border-indigo-200 dark:border-indigo-700 rounded-xl p-6"
            data-testid="section-moat-score"
          >
            <div className="flex items-center gap-6 flex-wrap">
              <div className="text-center">
                <div className={`text-7xl font-black ${gradeColor(s.grade)}`} data-testid="text-moat-grade">{s.grade}</div>
                <div className="text-xs text-gray-500 mt-1">Moat Grade</div>
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Overall Defensibility Score</span>
                  <span className="text-2xl font-bold text-indigo-600" data-testid="text-moat-overall">{s.overall}/100</span>
                </div>
                <Progress value={s.overall} className="h-3 mb-4" />
                <div className="grid grid-cols-4 gap-3">
                  {[
                    { key: "flywheel", label: "Flywheel",  icon: <Zap className="h-4 w-4 text-yellow-500" />,   val: s.components.flywheel },
                    { key: "rarity",   label: "Rarity",    icon: <Star className="h-4 w-4 text-purple-500" />,  val: s.components.rarity   },
                    { key: "network",  label: "Network",   icon: <Network className="h-4 w-4 text-blue-500" />, val: s.components.network  },
                    { key: "lockin",   label: "Lock-In",   icon: <Lock className="h-4 w-4 text-green-500" />,   val: s.components.lockin   },
                  ].map(c => (
                    <div key={c.key} className="bg-white dark:bg-gray-800 rounded-lg p-3 text-center border" data-testid={`card-component-${c.key}`}>
                      <div className="flex justify-center mb-1">{c.icon}</div>
                      <div className="text-xl font-bold text-gray-900 dark:text-white">{c.val}/25</div>
                      <div className="text-xs text-gray-500">{c.label}</div>
                      <Progress value={(c.val / 25) * 100} className="h-1 mt-2" />
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <p className="text-xs text-gray-400 mt-4">
              Refreshed {new Date(s.generatedAt).toLocaleTimeString()} · Pipeline v1.2.0 with stage 9 (Moat Data Flywheel)
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

            {/* ── flywheel ──────────────────────────────────────────────── */}
            <Card data-testid="card-flywheel">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <Zap className="h-4 w-4 text-yellow-500" />
                  Data Flywheel
                  <Badge variant="outline" className="ml-auto text-xs">Stage 9</Badge>
                </CardTitle>
                <p className="text-xs text-gray-500">encounter → validation → golden case → model improvement → better outcomes → more usage</p>
              </CardHeader>
              <CardContent className="space-y-3">
                {[
                  { label: "Total encounters recorded",  val: s.flywheel.totalEncounters.toLocaleString(),    icon: <Activity className="h-4 w-4 text-gray-400" />, testid: "text-fly-total" },
                  { label: "Validated encounters",        val: s.flywheel.validatedEncounters.toLocaleString(), icon: <Target className="h-4 w-4 text-green-500" />,  testid: "text-fly-validated" },
                  { label: "Golden case promotions",      val: s.flywheel.goldenPromotions.toLocaleString(),    icon: <Star className="h-4 w-4 text-yellow-500" />,   testid: "text-fly-golden" },
                  { label: "Velocity (last 24h)",         val: `${s.flywheel.velocity24h} encounters`,         icon: <TrendingUp className="h-4 w-4 text-blue-500" />,testid: "text-fly-velocity" },
                  { label: "Velocity (last 7d)",          val: `${s.flywheel.velocity7d} encounters`,          icon: <TrendingUp className="h-4 w-4 text-indigo-500" />, testid: "text-fly-velocity7" },
                  { label: "Validation rate",             val: pct(s.flywheel.validationRate),                 icon: <BarChart3 className="h-4 w-4 text-purple-500" />, testid: "text-fly-rate" },
                ].map(row => (
                  <div key={row.label} className="flex items-center justify-between py-1 border-b border-gray-50 dark:border-gray-800 last:border-0">
                    <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">{row.icon}{row.label}</div>
                    <span className="font-semibold text-sm text-gray-900 dark:text-white" data-testid={row.testid}>{row.val}</span>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* ── rare case engine ──────────────────────────────────────── */}
            <Card data-testid="card-rarity">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <Star className="h-4 w-4 text-purple-500" />
                  Rare Case Advantage
                </CardTitle>
                <p className="text-xs text-gray-500">
                  Rare presentations (&lt;1% frequency) get 2-3× learning weight — the Ada Health moat
                </p>
              </CardHeader>
              <CardContent className="space-y-3">
                {[
                  { label: "Total diagnoses catalogued", val: s.rarity.totalDiagnosesSeen.toString(), testid: "text-rare-total" },
                  { label: "Rare diagnoses (< 1%)",      val: s.rarity.rareDxCount.toString(),         testid: "text-rare-count", highlight: true },
                  { label: "Ultra-rare (< 0.1%)",        val: s.rarity.ultraRareDxCount.toString(),    testid: "text-rare-ultra", highlight: true },
                  { label: "Total encounters tracked",   val: s.rarity.totalEncounters.toString(),      testid: "text-rare-enc" },
                  { label: "Rare coverage rate",         val: pct(s.rarity.rareCoverageRate),            testid: "text-rare-rate" },
                ].map(row => (
                  <div key={row.label} className="flex items-center justify-between py-1 border-b border-gray-50 dark:border-gray-800 last:border-0">
                    <span className="text-sm text-gray-600 dark:text-gray-400">{row.label}</span>
                    <span
                      className={`font-semibold text-sm ${row.highlight ? "text-purple-600 dark:text-purple-400" : "text-gray-900 dark:text-white"}`}
                      data-testid={row.testid}
                    >{row.val}</span>
                  </div>
                ))}
                <div className="mt-2 bg-purple-50 dark:bg-purple-900/20 rounded-lg p-3 text-xs text-purple-700 dark:text-purple-300">
                  Ultra-rare cases receive a 3× learning weight boost — creating long-tail clinical superiority that generic LLMs cannot match
                </div>
              </CardContent>
            </Card>

            {/* ── cross-clinic network ──────────────────────────────────── */}
            <Card data-testid="card-network">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <Network className="h-4 w-4 text-blue-500" />
                  Cross-Clinic Learning Network
                </CardTitle>
                <p className="text-xs text-gray-500">
                  More clinics → more cases → better model → more clinics (true network effect)
                </p>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="grid grid-cols-3 gap-3 mb-2">
                  <div className="text-center bg-blue-50 dark:bg-blue-900/20 rounded-lg p-3">
                    <div className="text-2xl font-bold text-blue-600" data-testid="text-net-clinics">{s.network.activeClinicCount}</div>
                    <div className="text-xs text-gray-500">Active Clinics</div>
                  </div>
                  <div className="text-center bg-indigo-50 dark:bg-indigo-900/20 rounded-lg p-3">
                    <div className="text-2xl font-bold text-indigo-600" data-testid="text-net-cases">{s.network.totalNetworkCases.toLocaleString()}</div>
                    <div className="text-xs text-gray-500">Network Cases</div>
                  </div>
                  <div className="text-center bg-cyan-50 dark:bg-cyan-900/20 rounded-lg p-3">
                    <div className="text-2xl font-bold text-cyan-600" data-testid="text-net-multiplier">{s.network.networkMultiplier.toFixed(2)}×</div>
                    <div className="text-xs text-gray-500">Network Multiplier</div>
                  </div>
                </div>
                <div className="text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Specialty Breakdown</div>
                {(s.network.specialtyBreakdown.length > 0 ? s.network.specialtyBreakdown.slice(0, 6) : [
                  { specialty: "ENT", cases: 0, share: 0 },
                  { specialty: "Cardiology", cases: 0, share: 0 },
                  { specialty: "General", cases: 0, share: 0 },
                ]).map(sp => (
                  <div key={sp.specialty} className="space-y-0.5" data-testid={`row-specialty-${sp.specialty}`}>
                    <div className="flex justify-between text-xs">
                      <span className="text-gray-600 dark:text-gray-400">{sp.specialty}</span>
                      <span className="text-gray-900 dark:text-white font-medium">{sp.cases} ({pct(sp.share)})</span>
                    </div>
                    <Progress value={sp.share * 100} className="h-1" />
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* ── clinic lock-in ────────────────────────────────────────── */}
            <Card data-testid="card-lockin">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <Lock className="h-4 w-4 text-green-500" />
                  Clinic Lock-In Value
                </CardTitle>
                <p className="text-xs text-gray-500">
                  The more data a clinic generates, the harder it becomes to leave — accumulated intelligence is the switching cost
                </p>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="grid grid-cols-2 gap-3 mb-2">
                  <div className="text-center bg-green-50 dark:bg-green-900/20 rounded-lg p-3">
                    <div className="text-2xl font-bold text-green-600" data-testid="text-lock-high">{s.lockin.clinicsWithHighCost}</div>
                    <div className="text-xs text-gray-500">High/Very-High Lock-In</div>
                  </div>
                  <div className="text-center bg-emerald-50 dark:bg-emerald-900/20 rounded-lg p-3">
                    <div className="text-2xl font-bold text-emerald-600" data-testid="text-lock-patterns">{s.lockin.totalAccumulatedPatterns.toLocaleString()}</div>
                    <div className="text-xs text-gray-500">Accumulated Patterns</div>
                  </div>
                </div>
                {(clinicValues?.clinics ?? []).slice(0, 5).map((c: any, i: number) => (
                  <div key={c.clinicId} className="flex items-center justify-between py-1 border-b border-gray-50 dark:border-gray-800 last:border-0" data-testid={`row-clinic-${i}`}>
                    <div>
                      <div className="text-sm font-medium text-gray-800 dark:text-gray-200">{c.clinicId}</div>
                      <div className="text-xs text-gray-400">{c.totalEncounters} enc · {c.uniqueDiagnoses} dx</div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-bold text-gray-900 dark:text-white">{c.valueScore.toLocaleString()}</span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${costBadge(c.switchingCostLabel)}`}>
                        {c.switchingCostLabel}
                      </span>
                    </div>
                  </div>
                ))}
                {(clinicValues?.clinics ?? []).length === 0 && (
                  <p className="text-xs text-gray-400 italic">No clinic data yet — run the flywheel simulator below to populate</p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* ── golden dataset ────────────────────────────────────────────── */}
          <Card data-testid="card-golden-dataset">
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Database className="h-4 w-4 text-amber-500" />
                Golden Case Dataset — The Crown Jewel
              </CardTitle>
              <p className="text-xs text-gray-500">
                Proprietary clinical validation dataset that compounds over time. Competitors cannot replicate 50,000 validated cases with reasoning traces overnight.
              </p>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-3 gap-6 mb-4">
                <div className="text-center">
                  <div className="text-3xl font-black text-amber-600" data-testid="text-golden-total">{s.goldenDataset.total.toLocaleString()}</div>
                  <div className="text-xs text-gray-500 mt-1">Total Golden Cases</div>
                  <div className="text-xs text-gray-400">(target: 50,000)</div>
                  <Progress value={Math.min(100, (s.goldenDataset.total / 50000) * 100)} className="h-2 mt-2" />
                </div>
                <div className="text-center">
                  <div className="text-3xl font-black text-orange-600" data-testid="text-golden-auto">{s.goldenDataset.autoGenerated.toLocaleString()}</div>
                  <div className="text-xs text-gray-500 mt-1">Auto-Generated</div>
                  <div className="text-xs text-gray-400">from reconciliation failures</div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-black text-blue-600" data-testid="text-golden-specialties">{s.goldenDataset.specialtyCoverage}</div>
                  <div className="text-xs text-gray-500 mt-1">Specialties Covered</div>
                </div>
              </div>
              <div className="bg-amber-50 dark:bg-amber-900/10 border border-amber-200 dark:border-amber-800 rounded-lg p-4">
                <div className="flex items-start gap-2">
                  <Shield className="h-4 w-4 text-amber-600 mt-0.5 flex-shrink-0" />
                  <div className="text-xs text-amber-800 dark:text-amber-300 space-y-1">
                    <div className="font-semibold">IP Strategy Assessment</div>
                    <div>Each validated case adds to a proprietary clinical truth engine. The auto-generator harvests new golden cases from every reconciliation failure — turning system imperfections into competitive advantage. This dataset grows automatically without additional data entry.</div>
                    <div className="font-medium mt-2">
                      Flywheel velocity: {s.flywheel.velocity24h} encounters/day →
                      estimated {Math.round(s.flywheel.velocity24h * 0.15)} new golden cases/day at 15% validation rate
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* ── flywheel simulator ────────────────────────────────────────── */}
          <Card data-testid="card-simulator">
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <FlaskConical className="h-4 w-4 text-indigo-500" />
                Flywheel Simulator
                <Badge variant="outline" className="ml-auto text-xs">Demo</Badge>
              </CardTitle>
              <p className="text-xs text-gray-500">
                Simulate adding an encounter to the flywheel — observe moat metrics update in real time
              </p>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                <div className="space-y-1">
                  <Label className="text-xs" htmlFor="sim-clinic">Clinic ID</Label>
                  <Input
                    id="sim-clinic"
                    value={simClinic}
                    onChange={e => setSimClinic(e.target.value)}
                    className="h-8 text-sm"
                    data-testid="input-sim-clinic"
                  />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs" htmlFor="sim-complaint">Complaint</Label>
                  <Input
                    id="sim-complaint"
                    value={simComplaint}
                    onChange={e => setSimComplaint(e.target.value)}
                    className="h-8 text-sm"
                    data-testid="input-sim-complaint"
                  />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs" htmlFor="sim-diagnosis">Diagnosis</Label>
                  <Input
                    id="sim-diagnosis"
                    value={simDiagnosis}
                    onChange={e => setSimDiagnosis(e.target.value)}
                    className="h-8 text-sm"
                    data-testid="input-sim-diagnosis"
                  />
                </div>
                <div className="flex flex-col justify-between">
                  <div className="flex items-center gap-2 mt-5">
                    <input
                      type="checkbox"
                      id="sim-validated"
                      checked={simValidated}
                      onChange={e => setSimValidated(e.target.checked)}
                      data-testid="input-sim-validated"
                      className="h-4 w-4"
                    />
                    <Label className="text-xs" htmlFor="sim-validated">Validated</Label>
                  </div>
                </div>
              </div>
              <Button
                onClick={() => simulate.mutate()}
                disabled={simulate.isPending}
                className="w-full sm:w-auto"
                data-testid="button-run-flywheel-sim"
              >
                {simulate.isPending ? (
                  <><RefreshCw className="h-4 w-4 mr-2 animate-spin" /> Recording…</>
                ) : (
                  <><ChevronRight className="h-4 w-4 mr-1" /> Feed Flywheel</>
                )}
              </Button>

              <div className="mt-4 bg-gray-50 dark:bg-gray-800 rounded-lg p-4 text-xs text-gray-600 dark:text-gray-400">
                <div className="font-semibold mb-2 flex items-center gap-1">
                  <Users className="h-3 w-3" /> How the flywheel compounds
                </div>
                <div className="space-y-1">
                  {[
                    "1. Every triage completion → recorded in cross-clinic network",
                    "2. Rare presentations detected → 2-3× learning weight assigned",
                    "3. Physician-validated encounters → promoted to golden dataset",
                    "4. Specialty weights updated → model becomes more accurate",
                    "5. Clinic value score rises → switching cost increases",
                    "6. More accurate model → attracts more clinics → loop repeats",
                  ].map(step => (
                    <div key={step} className="flex items-start gap-1">
                      <ChevronRight className="h-3 w-3 mt-0.5 text-indigo-400 flex-shrink-0" />
                      {step}
                    </div>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* ── moat vs competitors ──────────────────────────────────────── */}
          <Card data-testid="card-competitive">
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Shield className="h-4 w-4 text-red-500" />
                Competitive Defensibility Analysis
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b">
                      <th className="text-left py-2 text-gray-500 font-medium">Moat Component</th>
                      <th className="text-center py-2 text-indigo-600 font-semibold">Auralyn</th>
                      <th className="text-center py-2 text-gray-400 font-medium">Epic (internal)</th>
                      <th className="text-center py-2 text-gray-400 font-medium">Generic LLM</th>
                      <th className="text-center py-2 text-gray-400 font-medium">Time to copy</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      { component: "Clinical rule logic", auralyn: "✅", epic: "✅", llm: "✅", time: "6-12 months" },
                      { component: "Golden case dataset", auralyn: "✅ Growing", epic: "⚠️ Silo'd", llm: "❌ None", time: "3-5 years" },
                      { component: "Cross-clinic network effects", auralyn: "✅ Active", epic: "❌ Locked", llm: "❌ None", time: "Never (requires trust)" },
                      { component: "Rare case coverage", auralyn: `✅ ${s.rarity.rareDxCount} dx`, epic: "⚠️ Partial", llm: "❌ Undertrained", time: "2-4 years" },
                      { component: "Specialty RLHF tuning", auralyn: "✅ ENT/Pulm", epic: "⚠️ Generic", llm: "❌ None", time: "18-24 months" },
                      { component: "HIPAA + FDA audit chain", auralyn: "✅", epic: "✅", llm: "❌", time: "6-12 months" },
                      { component: "Clinic switching cost", auralyn: `✅ Score: ${s.lockin.averageValueScore}`, epic: "✅ High", llm: "❌ None", time: "Data-dependent" },
                    ].map((row, i) => (
                      <tr key={i} className="border-b border-gray-50 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50">
                        <td className="py-2 text-gray-700 dark:text-gray-300 font-medium">{row.component}</td>
                        <td className="py-2 text-center font-medium text-indigo-700 dark:text-indigo-300">{row.auralyn}</td>
                        <td className="py-2 text-center text-gray-500">{row.epic}</td>
                        <td className="py-2 text-center text-gray-500">{row.llm}</td>
                        <td className="py-2 text-center text-orange-600 dark:text-orange-400">{row.time}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
