export type LearningDomain =
  | "clinical_reasoning"
  | "conversation_interface"
  | "risk_prediction"
  | "workflow_optimization"
  | "safety_gating"
  | "billing_documentation";

export interface ImprovementContract {
  component_name: string;
  display_name: string;
  description: string;
  domain: LearningDomain;
  layer: string;
  emits_trace: boolean;
  tunable_parameters: string[];
  proposal_targets: string[];
  regression_suite: string[];
  learning_enabled: boolean;
  safety_guard: boolean;
  trace_fields?: string[];
  known_gaps?: string[];
  improvement_priority: "critical" | "high" | "medium" | "low";
}

export const ALL_CONTRACTS: ImprovementContract[] = [
  // ── CLINICAL REASONING ────────────────────────────────────────────────────

  {
    component_name: "autonomous_intake_engine",
    display_name: "Autonomous Intake Engine",
    description: "Multi-turn NLP intake for 9 complaints. Collects modifiers, asks dynamic follow-up questions, and detects compound red flags.",
    domain: "clinical_reasoning",
    layer: "Completion Module 1",
    emits_trace: true,
    tunable_parameters: ["question_priority_order", "red_flag_threshold", "compound_pattern_weights", "follow_up_branching"],
    proposal_targets: ["CORE_QUESTIONS", "GLOBAL_SECONDARY", "RED_FLAG_PATTERNS"],
    regression_suite: ["sore_throat", "cough", "chest_pain", "uti", "fever", "abdominal_pain"],
    learning_enabled: true,
    safety_guard: true,
    trace_fields: ["questions_asked", "signals_detected", "red_flags_triggered", "triage_level"],
    known_gaps: [],
    improvement_priority: "critical",
  },

  {
    component_name: "differential_skill",
    display_name: "Differential Diagnosis Engine",
    description: "Per-complaint ranked differential with ruling-in/ruling-out factor updates per symptom. Covers 9 complaint sets with 50+ diagnoses.",
    domain: "clinical_reasoning",
    layer: "Telemedicine Assistant",
    emits_trace: true,
    tunable_parameters: ["diagnosis_weights", "graph_edge_weights", "score_threshold", "ruling_in_factors", "ruling_out_factors"],
    proposal_targets: ["CLUSTER_SCORING_RULES", "KNOWLEDGE_GRAPH", "DISP_RULES"],
    regression_suite: ["chest_pain", "abdominal_pain", "cough", "sore_throat", "fever"],
    learning_enabled: true,
    safety_guard: true,
    trace_fields: ["differential_scores", "signals_detected", "complaint"],
    known_gaps: [],
    improvement_priority: "critical",
  },

  {
    component_name: "disposition_layer",
    display_name: "Disposition / Triage Engine",
    description: "Rule-based disposition engine with 241 rules loaded from Google Sheets. Produces home_care / urgent_care / er_now / prescription dispositions.",
    domain: "clinical_reasoning",
    layer: "Core Engine",
    emits_trace: true,
    tunable_parameters: ["triage_thresholds", "rule_weights", "disposition_overrides"],
    proposal_targets: ["DISP_RULES", "CLUSTER_SCORING_RULES"],
    regression_suite: ["chest_pain", "sepsis", "sore_throat", "uti", "fever"],
    learning_enabled: true,
    safety_guard: true,
    trace_fields: ["rules_triggered", "final_output.disposition", "final_output.confidence"],
    known_gaps: [],
    improvement_priority: "critical",
  },

  {
    component_name: "red_flag_detector",
    display_name: "Red Flag Detector",
    description: "Compound red-flag detection requiring ≥60% pattern match across symptom clusters to avoid false positives.",
    domain: "safety_gating",
    layer: "Core Engine",
    emits_trace: true,
    tunable_parameters: ["compound_threshold", "flag_weights", "pattern_match_minimum"],
    proposal_targets: ["RED_FLAG_PATTERNS", "DISP_RULES"],
    regression_suite: ["chest_pain", "fever", "sore_throat", "abdominal_pain"],
    learning_enabled: true,
    safety_guard: true,
    trace_fields: ["signals_detected", "rules_triggered", "runtime_flags"],
    known_gaps: [],
    improvement_priority: "critical",
  },

  {
    component_name: "clinical_scoring",
    display_name: "Clinical Scoring Systems",
    description: "Integrated clinical scoring: Centor, CURB-65, HEART, qSOFA, PERC, WELLS_PE. Configured via CSV.",
    domain: "clinical_reasoning",
    layer: "Diagnostics & Scoring",
    emits_trace: true,
    tunable_parameters: ["score_thresholds", "component_weights", "cutoff_values"],
    proposal_targets: ["CLUSTER_SCORING_RULES"],
    regression_suite: ["chest_pain", "cough", "fever", "sore_throat"],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: ["rules_triggered"],
    known_gaps: ["scoring thresholds are fixed, not learned from outcomes"],
    improvement_priority: "medium",
  },

  {
    component_name: "care_pathway_executor",
    display_name: "Care Pathway Automation",
    description: "11 pathways across 9 complaints with labs, meds, referrals, follow-ups, monitoring, contraindications, and escalation criteria.",
    domain: "workflow_optimization",
    layer: "Completion Module 3",
    emits_trace: true,
    tunable_parameters: ["pathway_steps", "escalation_criteria", "contraindication_list"],
    proposal_targets: ["PATHWAY_REGISTRY", "MED_TO_CONDITION_TRIGGERS"],
    regression_suite: ["sore_throat", "cough", "chest_pain", "uti"],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: ["rules_triggered"],
    known_gaps: ["no outcome-based pathway refinement yet"],
    improvement_priority: "high",
  },

  {
    component_name: "complaint_question_engine",
    display_name: "Complaint Question Bundle Engine",
    description: "Dynamic follow-up question selection per complaint — 6 questions each, ordered by clinical yield.",
    domain: "clinical_reasoning",
    layer: "Core Engine",
    emits_trace: true,
    tunable_parameters: ["question_priority_order", "branching_conditions"],
    proposal_targets: ["CORE_QUESTIONS"],
    regression_suite: ["sore_throat", "cough", "chest_pain", "uti", "fever", "rash", "ear_pain"],
    learning_enabled: true,
    safety_guard: false,
    trace_fields: ["questions_asked"],
    known_gaps: [],
    improvement_priority: "high",
  },

  // ── RISK PREDICTION ───────────────────────────────────────────────────────

  {
    component_name: "predictive_risk_model",
    display_name: "Predictive Risk Model",
    description: "Multi-factor scoring for admission risk, deterioration risk, and 30-day readmission risk. Per-complaint factor library with learned weights.",
    domain: "risk_prediction",
    layer: "Completion Module 5",
    emits_trace: true,
    tunable_parameters: ["feature_weights", "risk_thresholds", "complaint_factors"],
    proposal_targets: ["RISK_FACTOR_LIBRARY"],
    regression_suite: ["chest_pain", "fever", "uti", "cough", "abdominal_pain"],
    learning_enabled: true,
    safety_guard: true,
    trace_fields: ["differential_scores", "signals_detected", "modifier_intake"],
    known_gaps: [],
    improvement_priority: "high",
  },

  {
    component_name: "reinforcement_engine",
    display_name: "Reinforcement Learning Engine",
    description: "Q-learning policy over complaint×disposition state-action space. Reward: +1 correct, +0.5 improvement, −1 undertriage, −2 dangerous miss.",
    domain: "risk_prediction",
    layer: "Self-Developing AI — Level 7",
    emits_trace: true,
    tunable_parameters: ["learning_rate", "reward_weights", "q_table_discount"],
    proposal_targets: ["DISP_RULES", "CLUSTER_SCORING_RULES"],
    regression_suite: ["sore_throat", "cough", "chest_pain", "uti", "fever"],
    learning_enabled: true,
    safety_guard: false,
    trace_fields: ["final_output.disposition", "complaint", "signals_detected"],
    known_gaps: ["no safety guard on Q-table updates — could reinforce bad decisions without gating"],
    improvement_priority: "high",
  },

  {
    component_name: "knowledge_graph",
    display_name: "Clinical Knowledge Graph",
    description: "Symptom→diagnosis weighted edge graph seeded with 29 clinical relationships across 9 complaints. Confirmed/refuted feedback updates weights.",
    domain: "risk_prediction",
    layer: "Self-Developing AI — Level 8",
    emits_trace: true,
    tunable_parameters: ["edge_weights", "confirmation_learning_rate", "refutation_penalty"],
    proposal_targets: ["KNOWLEDGE_GRAPH", "CLUSTER_SCORING_RULES"],
    regression_suite: ["sore_throat", "chest_pain", "cough", "uti", "fever"],
    learning_enabled: true,
    safety_guard: false,
    trace_fields: ["differential_scores", "signals_detected"],
    known_gaps: ["no safety guard — graph updates not gated by regression"],
    improvement_priority: "medium",
  },

  // ── CONVERSATION INTERFACE ────────────────────────────────────────────────

  {
    component_name: "patient_interface_agent",
    display_name: "Patient Interface Agent (WhatsApp / Telegram)",
    description: "Conversational intake via WhatsApp and Telegram. Collects symptoms, modifiers, and answers through natural language.",
    domain: "conversation_interface",
    layer: "Messaging Channels",
    emits_trace: true,
    tunable_parameters: ["question_wording", "reading_level", "response_length", "language_tone"],
    proposal_targets: ["OUTPUT_TEMPLATES", "QUESTION_WORDING", "CORE_QUESTIONS"],
    regression_suite: ["readability_tests", "completion_rate", "abandonment_rate"],
    learning_enabled: false,
    safety_guard: false,
    trace_fields: ["questions_asked", "modifier_intake"],
    known_gaps: ["no completion rate tracking", "no readability scoring", "no abandonment detection"],
    improvement_priority: "medium",
  },

  {
    component_name: "telemedicine_session",
    display_name: "Telemedicine Visit Console",
    description: "Real-time intelligence layer during telemedicine visits. Produces differential, safety alerts, medication suggestions, and discharge messages.",
    domain: "conversation_interface",
    layer: "Telemedicine Assistant",
    emits_trace: true,
    tunable_parameters: ["alert_sensitivity", "differential_display_count", "discharge_template"],
    proposal_targets: ["OUTPUT_TEMPLATES", "QUESTION_WORDING"],
    regression_suite: ["sore_throat", "chest_pain", "uti", "fever", "cough"],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: ["questions_asked", "signals_detected", "differential_scores"],
    known_gaps: ["session data not fed back into improvement loop"],
    improvement_priority: "high",
  },

  // ── WORKFLOW OPTIMIZATION ─────────────────────────────────────────────────

  {
    component_name: "clinician_copilot",
    display_name: "Clinician Copilot",
    description: "7 suggestion categories: scoring hints, differential DDx, red flag reminders, pending questions, documentation hints, safety checks, pathway suggestions.",
    domain: "workflow_optimization",
    layer: "Completion Module 4",
    emits_trace: false,
    tunable_parameters: ["suggestion_thresholds", "hint_sensitivity"],
    proposal_targets: ["OUTPUT_TEMPLATES"],
    regression_suite: ["sore_throat", "chest_pain", "cough"],
    learning_enabled: false,
    safety_guard: false,
    trace_fields: [],
    known_gaps: ["does not emit trace", "no learning from physician acceptance/rejection of hints", "no safety guard"],
    improvement_priority: "high",
  },

  {
    component_name: "rl_policy_trainer",
    display_name: "RL Policy Trainer",
    description: "Reward function: +1 correct disposition, +1 improved, −1 worsened, −2 safety miss. Persists policy and history.",
    domain: "workflow_optimization",
    layer: "Completion Module 2",
    emits_trace: true,
    tunable_parameters: ["reward_weights", "policy_update_frequency"],
    proposal_targets: ["DISP_RULES"],
    regression_suite: ["all_complaints"],
    learning_enabled: true,
    safety_guard: false,
    trace_fields: ["final_output.disposition", "complaint"],
    known_gaps: ["no safety guard on policy promotion"],
    improvement_priority: "medium",
  },

  {
    component_name: "physician_review_queue",
    display_name: "Physician Review Queue",
    description: "Firestore-backed case review and signoff system. Manages queue, assigns reviewers, tracks approval/override rates.",
    domain: "workflow_optimization",
    layer: "Clinical Operations",
    emits_trace: false,
    tunable_parameters: ["review_routing_logic", "auto_approve_thresholds"],
    proposal_targets: ["REVIEW_ROUTING_RULES"],
    regression_suite: [],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: [],
    known_gaps: ["does not emit trace", "override patterns not fed into improvement loop", "no regression suite"],
    improvement_priority: "medium",
  },

  // ── BILLING & DOCUMENTATION ───────────────────────────────────────────────

  {
    component_name: "icd_cpt_coder",
    display_name: "ICD-10 / CPT Auto-Coder",
    description: "Auto-coding by complaint × disposition. Telemedicine modifier 95. Lab CPT codes. RVU values per code.",
    domain: "billing_documentation",
    layer: "Telemedicine Assistant",
    emits_trace: false,
    tunable_parameters: ["code_mapping_table"],
    proposal_targets: ["ICD_CPT_MAPPING"],
    regression_suite: [],
    learning_enabled: false,
    safety_guard: false,
    trace_fields: [],
    known_gaps: ["no trace emission", "no learning from billing rejections", "no regression suite", "no safety guard"],
    improvement_priority: "low",
  },

  {
    component_name: "medication_safety_layer",
    display_name: "Medication Safety Layer",
    description: "Allergy cross-reaction detection, pregnancy contraindications, renal impairment warnings, 11 drug-drug interaction rules.",
    domain: "safety_gating",
    layer: "Telemedicine Assistant",
    emits_trace: false,
    tunable_parameters: ["interaction_rules", "allergy_cross_reactions", "renal_thresholds"],
    proposal_targets: ["MED_TO_CONDITION_TRIGGERS", "MEDICATION_SAFETY_RULES"],
    regression_suite: ["medication_safety_cases"],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: [],
    known_gaps: ["does not emit trace", "interaction rules are static — no learning from adverse outcomes"],
    improvement_priority: "high",
  },

  {
    component_name: "chart_note_generator",
    display_name: "Chart Note / Documentation Generator",
    description: "Auto-generates HPI, assessment, plan, disposition, safety netting chart note per telemedicine session.",
    domain: "billing_documentation",
    layer: "Telemedicine Assistant",
    emits_trace: false,
    tunable_parameters: ["note_template_structure", "hpi_detail_level"],
    proposal_targets: ["OUTPUT_TEMPLATES"],
    regression_suite: [],
    learning_enabled: false,
    safety_guard: false,
    trace_fields: [],
    known_gaps: ["no trace emission", "template not improved from physician edits", "no regression suite", "no safety guard"],
    improvement_priority: "low",
  },

  // ── SELF-DEVELOPING AI ────────────────────────────────────────────────────

  {
    component_name: "trace_recorder",
    display_name: "Trace Recorder (L1)",
    description: "Records full reasoning paths per case. Questions asked, rules triggered, differential scores, disposition, missing data, runtime flags.",
    domain: "workflow_optimization",
    layer: "Self-Developing AI — Level 1",
    emits_trace: true,
    tunable_parameters: ["trace_schema_fields", "retention_policy"],
    proposal_targets: [],
    regression_suite: ["all_complaints"],
    learning_enabled: false,
    safety_guard: false,
    trace_fields: ["all"],
    known_gaps: ["no self-improvement loop for the trace recorder itself"],
    improvement_priority: "low",
  },

  {
    component_name: "gold_case_evaluator",
    display_name: "Gold Case Evaluator (L2)",
    description: "Compares system output against 10 physician-reviewed gold cases. Checks disposition match, diagnosis match, required questions, dangerous misses.",
    domain: "clinical_reasoning",
    layer: "Self-Developing AI — Level 2",
    emits_trace: true,
    tunable_parameters: ["comparison_strictness", "dangerous_miss_weight"],
    proposal_targets: ["GOLD_CASES"],
    regression_suite: ["all_complaints"],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: ["final_output", "differential_scores", "questions_asked"],
    known_gaps: ["only 10 gold cases — needs expansion across all 78 complaint pipelines"],
    improvement_priority: "high",
  },

  {
    component_name: "failure_classifier",
    display_name: "Failure Classifier (L3)",
    description: "13 canonical failure types with severity scoring and actionable hints. Maps each failed case to a named problem category.",
    domain: "clinical_reasoning",
    layer: "Self-Developing AI — Level 3",
    emits_trace: true,
    tunable_parameters: ["severity_thresholds", "failure_type_weights"],
    proposal_targets: [],
    regression_suite: ["all_complaints"],
    learning_enabled: false,
    safety_guard: false,
    trace_fields: ["final_output", "questions_asked"],
    known_gaps: ["classifier rules are deterministic — could improve with ML classification over time"],
    improvement_priority: "medium",
  },

  {
    component_name: "proposal_engine",
    display_name: "Proposal Engine (L4)",
    description: "Maps failure types to proposal types. Generates evidence-linked, deduplicated, risk-scored proposals into a review queue.",
    domain: "workflow_optimization",
    layer: "Self-Developing AI — Level 4",
    emits_trace: true,
    tunable_parameters: ["failure_to_proposal_mapping", "risk_thresholds"],
    proposal_targets: ["PROPOSED_RULE_CHANGES"],
    regression_suite: ["all_complaints"],
    learning_enabled: false,
    safety_guard: true,
    trace_fields: ["final_output"],
    known_gaps: ["proposal quality not yet scored by acceptance rate — no feedback loop on proposal usefulness"],
    improvement_priority: "medium",
  },

  {
    component_name: "improvement_orchestrator",
    display_name: "Autonomous Improvement Orchestrator (L10)",
    description: "Runs the full loop: load gold cases → build traces → compare → classify failures → generate proposals → update RL → update knowledge graph.",
    domain: "workflow_optimization",
    layer: "Self-Developing AI — Level 10",
    emits_trace: true,
    tunable_parameters: ["cycle_frequency", "max_cases_per_cycle", "complaint_priorities"],
    proposal_targets: [],
    regression_suite: ["all_complaints"],
    learning_enabled: true,
    safety_guard: true,
    trace_fields: ["all"],
    known_gaps: [],
    improvement_priority: "low",
  },
];
