import { PackQuestionRow } from "../../shared/packQuestionRows";

export const packQuestionRows: PackQuestionRow[] = [
  {
    id: "pq_card_chest_pain_1",
    packId: "card_chest_pain",
    questionId: "sob",
    prompt: "Any shortness of breath?",
    type: "yes_no",
    priority: 1,
    required: true,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_card_chest_pain_2",
    packId: "card_chest_pain",
    questionId: "radiation",
    prompt: "Pain to arm, jaw, or back?",
    type: "yes_no",
    priority: 2,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_card_chest_pain_3",
    packId: "card_chest_pain",
    questionId: "exertional",
    prompt: "Triggered or worse with exertion?",
    type: "yes_no",
    priority: 3,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_card_chest_pain_4",
    packId: "card_chest_pain",
    questionId: "fainting",
    prompt: "Any fainting or near-fainting?",
    type: "yes_no",
    priority: 4,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_card_chest_pain_5",
    packId: "card_chest_pain",
    questionId: "sweating_nausea",
    prompt: "Cold sweat or nausea?",
    type: "yes_no",
    priority: 5,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_card_chest_pain_6",
    packId: "card_chest_pain",
    questionId: "tearing",
    prompt: "Sudden tearing pain to the back?",
    type: "yes_no",
    priority: 6,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_ortho_back_pain_1",
    packId: "ortho_back_pain",
    questionId: "injury",
    prompt: "Any fall, lifting injury, or trauma?",
    type: "yes_no",
    priority: 1,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_ortho_back_pain_2",
    packId: "ortho_back_pain",
    questionId: "leg_weakness",
    prompt: "Any leg weakness?",
    type: "yes_no",
    priority: 2,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_ortho_back_pain_3",
    packId: "ortho_back_pain",
    questionId: "groin_numbness",
    prompt: "Any numbness in the groin area?",
    type: "yes_no",
    priority: 3,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_ortho_back_pain_4",
    packId: "ortho_back_pain",
    questionId: "bowel_bladder",
    prompt: "Any loss of bowel or bladder control?",
    type: "yes_no",
    priority: 4,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_ortho_back_pain_5",
    packId: "ortho_back_pain",
    questionId: "fever",
    prompt: "Any fever?",
    type: "yes_no",
    priority: 5,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_ortho_back_pain_6",
    packId: "ortho_back_pain",
    questionId: "ivdu_cancer",
    prompt: "IV drug use, cancer, or immune suppression?",
    type: "yes_no",
    priority: 6,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_pulm_cough_1",
    packId: "pulm_cough",
    questionId: "duration",
    prompt: "How long have you had the cough?",
    type: "duration",
    priority: 1,
    required: true,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_pulm_cough_2",
    packId: "pulm_cough",
    questionId: "sob",
    prompt: "Any shortness of breath?",
    type: "yes_no",
    priority: 2,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_pulm_cough_3",
    packId: "pulm_cough",
    questionId: "chest_pain",
    prompt: "Any chest pain?",
    type: "yes_no",
    priority: 3,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_pulm_cough_4",
    packId: "pulm_cough",
    questionId: "fever",
    prompt: "Any fever?",
    type: "yes_no",
    priority: 4,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_pulm_cough_5",
    packId: "pulm_cough",
    questionId: "blood",
    prompt: "Any coughing up blood?",
    type: "yes_no",
    priority: 5,
    required: false,
    isActive: true,
    version: 1,
  },
  {
    id: "pq_pulm_cough_6",
    packId: "pulm_cough",
    questionId: "asthma_copd",
    prompt: "Asthma or COPD history?",
    type: "yes_no",
    priority: 6,
    required: false,
    isActive: true,
    version: 1,
  },
];
