import { ClinicalKnowledgeGraph } from "./knowledgeGraphTypes";

export const clinicalKnowledgeGraph: ClinicalKnowledgeGraph = {
  nodes: [
    { id: "complaint:cough", type: "complaint", label: "Cough" },
    { id: "complaint:chest_pain", type: "complaint", label: "Chest Pain" },
    { id: "complaint:headache", type: "complaint", label: "Headache" },
    { id: "complaint:dizziness", type: "complaint", label: "Dizziness" },
    { id: "complaint:sore_throat", type: "complaint", label: "Sore Throat" },
    { id: "complaint:fever", type: "complaint", label: "Fever" },
    { id: "complaint:ear_pain", type: "complaint", label: "Ear Pain" },
    { id: "complaint:breathlessness", type: "complaint", label: "Breathlessness" },

    { id: "symptom:fever", type: "symptom", label: "Fever" },
    { id: "symptom:sob", type: "symptom", label: "Shortness of Breath" },
    { id: "symptom:chest_pain", type: "symptom", label: "Chest Pain" },
    { id: "symptom:worst_headache", type: "symptom", label: "Worst Headache of Life" },
    { id: "symptom:diaphoresis", type: "symptom", label: "Diaphoresis" },
    { id: "symptom:tearing_pain", type: "symptom", label: "Tearing Pain" },
    { id: "symptom:trismus", type: "symptom", label: "Trismus" },
    { id: "symptom:stridor", type: "symptom", label: "Stridor" },
    { id: "symptom:petechiae", type: "symptom", label: "Petechiae" },
    { id: "symptom:mastoid_tenderness", type: "symptom", label: "Mastoid Tenderness" },
    { id: "symptom:unilateral_weakness", type: "symptom", label: "Unilateral Weakness" },

    { id: "question:duration", type: "question", label: "How long has this been going on?" },
    { id: "question:fever", type: "question", label: "Do you have fever?" },
    { id: "question:sob", type: "question", label: "Do you have shortness of breath?" },
    { id: "question:worst", type: "question", label: "Is this the worst headache of your life?" },
    { id: "question:chest_character", type: "question", label: "What does the pain feel like?" },
    { id: "question:exertion", type: "question", label: "Does it worsen with exertion?" },
    { id: "question:swallow_difficulty", type: "question", label: "Do you have difficulty swallowing?" },
    { id: "question:hearing_change", type: "question", label: "Have you noticed hearing changes?" },
    { id: "question:rash", type: "question", label: "Do you have any rash?" },
    { id: "question:positional", type: "question", label: "Is it related to position changes?" },

    { id: "skill:red_flag_detection", type: "skill", label: "Red Flag Detection" },
    { id: "skill:pneumonia_risk", type: "skill", label: "Pneumonia Risk" },
    { id: "skill:mi_risk", type: "skill", label: "MI Risk" },
    { id: "skill:sah_risk", type: "skill", label: "Subarachnoid Hemorrhage Risk" },
    { id: "skill:pe_risk", type: "skill", label: "Pulmonary Embolism Risk" },
    { id: "skill:stroke_risk", type: "skill", label: "Stroke Risk" },
    { id: "skill:sepsis_risk", type: "skill", label: "Sepsis Risk" },
    { id: "skill:peritonsillar_abscess", type: "skill", label: "Peritonsillar Abscess Detection" },
    { id: "skill:mastoiditis", type: "skill", label: "Mastoiditis Detection" },
    { id: "skill:respiratory_failure", type: "skill", label: "Respiratory Failure Assessment" },

    { id: "engine:redFlagEngine", type: "engine", label: "Red Flag Engine" },
    { id: "engine:bayesianDifferentialEngine", type: "engine", label: "Bayesian Differential Engine" },
    { id: "engine:nextQuestionSelector", type: "engine", label: "Next Question Selector" },
    { id: "engine:protocolSelectionEngine", type: "engine", label: "Protocol Selection Engine" },
    { id: "engine:caseSimilarityEngine", type: "engine", label: "Case Similarity Engine" },
    { id: "engine:clusterScoringEngine", type: "engine", label: "Cluster Scoring Engine" },
    { id: "engine:temporalRiskEngine", type: "engine", label: "Temporal Risk Engine" },
    { id: "engine:dispositionEngine", type: "engine", label: "Disposition Engine" },
    { id: "engine:confidenceCalibrationEngine", type: "engine", label: "Confidence Calibration Engine" },

    { id: "diagnosis:pneumonia", type: "diagnosis", label: "Pneumonia" },
    { id: "diagnosis:viral_uri", type: "diagnosis", label: "Viral URI" },
    { id: "diagnosis:acs", type: "diagnosis", label: "Acute Coronary Syndrome" },
    { id: "diagnosis:aortic_dissection", type: "diagnosis", label: "Aortic Dissection" },
    { id: "diagnosis:sah", type: "diagnosis", label: "Subarachnoid Hemorrhage" },
    { id: "diagnosis:stroke", type: "diagnosis", label: "Stroke" },
    { id: "diagnosis:bppv", type: "diagnosis", label: "BPPV" },
    { id: "diagnosis:meningitis", type: "diagnosis", label: "Meningitis" },
    { id: "diagnosis:strep_pharyngitis", type: "diagnosis", label: "Strep Pharyngitis" },
    { id: "diagnosis:otitis_media", type: "diagnosis", label: "Otitis Media" },
    { id: "diagnosis:mastoiditis_dx", type: "diagnosis", label: "Mastoiditis" },
    { id: "diagnosis:peritonsillar_abscess_dx", type: "diagnosis", label: "Peritonsillar Abscess" },
    { id: "diagnosis:asthma_exacerbation", type: "diagnosis", label: "Asthma Exacerbation" },
    { id: "diagnosis:meningococcemia", type: "diagnosis", label: "Meningococcemia" },

    { id: "protocol:cdc_respiratory", type: "protocol", label: "CDC Respiratory Protocol" },
    { id: "protocol:acep_aha_chest_pain", type: "protocol", label: "ACEP/AHA Chest Pain Protocol" },
    { id: "protocol:headache_emergency", type: "protocol", label: "Emergency Headache Protocol" },
    { id: "protocol:neurology_triage", type: "protocol", label: "AAN Neurology Triage Protocol" },
    { id: "protocol:ent_triage", type: "protocol", label: "AAO-HNS ENT Triage Protocol" },
    { id: "protocol:pharyngitis", type: "protocol", label: "IDSA Pharyngitis Protocol" },
    { id: "protocol:febrile_illness", type: "protocol", label: "NICE/CDC Febrile Illness Protocol" },
    { id: "protocol:respiratory_emergency", type: "protocol", label: "BTS Respiratory Emergency Protocol" },

    { id: "disposition:self_care", type: "disposition", label: "Self Care" },
    { id: "disposition:urgent_care", type: "disposition", label: "Urgent Care" },
    { id: "disposition:er_now", type: "disposition", label: "ER Now" },
  ],
  edges: [
    { id: "e1", from: "complaint:cough", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e2", from: "complaint:cough", to: "skill:pneumonia_risk", relation: "requires", weight: 1 },
    { id: "e3", from: "complaint:cough", to: "question:duration", relation: "asks", weight: 0.7 },
    { id: "e4", from: "complaint:cough", to: "question:fever", relation: "asks", weight: 0.9 },
    { id: "e5", from: "complaint:cough", to: "question:sob", relation: "asks", weight: 1 },
    { id: "e6", from: "complaint:cough", to: "protocol:cdc_respiratory", relation: "governed_by", weight: 1 },
    { id: "e7", from: "complaint:cough", to: "diagnosis:pneumonia", relation: "suggests", weight: 0.8 },
    { id: "e8", from: "complaint:cough", to: "diagnosis:viral_uri", relation: "suggests", weight: 0.6 },

    { id: "e9", from: "complaint:chest_pain", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e10", from: "complaint:chest_pain", to: "skill:mi_risk", relation: "requires", weight: 1 },
    { id: "e10b", from: "complaint:chest_pain", to: "skill:pe_risk", relation: "requires", weight: 0.8 },
    { id: "e11", from: "complaint:chest_pain", to: "protocol:acep_aha_chest_pain", relation: "governed_by", weight: 1 },
    { id: "e12", from: "complaint:chest_pain", to: "diagnosis:acs", relation: "suggests", weight: 0.9 },
    { id: "e12b", from: "complaint:chest_pain", to: "diagnosis:aortic_dissection", relation: "suggests", weight: 0.7 },
    { id: "e12c", from: "complaint:chest_pain", to: "question:chest_character", relation: "asks", weight: 0.9 },
    { id: "e12d", from: "complaint:chest_pain", to: "question:exertion", relation: "asks", weight: 0.85 },

    { id: "e13", from: "complaint:headache", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e14", from: "complaint:headache", to: "skill:sah_risk", relation: "requires", weight: 1 },
    { id: "e15", from: "complaint:headache", to: "question:worst", relation: "asks", weight: 1 },
    { id: "e16", from: "complaint:headache", to: "protocol:headache_emergency", relation: "governed_by", weight: 1 },
    { id: "e17", from: "complaint:headache", to: "diagnosis:sah", relation: "suggests", weight: 0.8 },
    { id: "e17b", from: "complaint:headache", to: "diagnosis:meningitis", relation: "suggests", weight: 0.6 },

    { id: "e30", from: "complaint:dizziness", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e31", from: "complaint:dizziness", to: "skill:stroke_risk", relation: "requires", weight: 1 },
    { id: "e32", from: "complaint:dizziness", to: "protocol:neurology_triage", relation: "governed_by", weight: 1 },
    { id: "e33", from: "complaint:dizziness", to: "diagnosis:stroke", relation: "suggests", weight: 0.7 },
    { id: "e34", from: "complaint:dizziness", to: "diagnosis:bppv", relation: "suggests", weight: 0.6 },
    { id: "e35", from: "complaint:dizziness", to: "question:positional", relation: "asks", weight: 0.8 },

    { id: "e40", from: "complaint:sore_throat", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e41", from: "complaint:sore_throat", to: "skill:peritonsillar_abscess", relation: "requires", weight: 0.9 },
    { id: "e42", from: "complaint:sore_throat", to: "protocol:pharyngitis", relation: "governed_by", weight: 1 },
    { id: "e43", from: "complaint:sore_throat", to: "diagnosis:strep_pharyngitis", relation: "suggests", weight: 0.7 },
    { id: "e44", from: "complaint:sore_throat", to: "diagnosis:peritonsillar_abscess_dx", relation: "suggests", weight: 0.5 },
    { id: "e45", from: "complaint:sore_throat", to: "question:swallow_difficulty", relation: "asks", weight: 0.9 },

    { id: "e50", from: "complaint:fever", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e51", from: "complaint:fever", to: "skill:sepsis_risk", relation: "requires", weight: 1 },
    { id: "e52", from: "complaint:fever", to: "protocol:febrile_illness", relation: "governed_by", weight: 1 },
    { id: "e53", from: "complaint:fever", to: "diagnosis:meningococcemia", relation: "suggests", weight: 0.6 },
    { id: "e54", from: "complaint:fever", to: "question:rash", relation: "asks", weight: 0.8 },

    { id: "e60", from: "complaint:ear_pain", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e61", from: "complaint:ear_pain", to: "skill:mastoiditis", relation: "requires", weight: 0.9 },
    { id: "e62", from: "complaint:ear_pain", to: "protocol:ent_triage", relation: "governed_by", weight: 1 },
    { id: "e63", from: "complaint:ear_pain", to: "diagnosis:otitis_media", relation: "suggests", weight: 0.7 },
    { id: "e64", from: "complaint:ear_pain", to: "diagnosis:mastoiditis_dx", relation: "suggests", weight: 0.4 },
    { id: "e65", from: "complaint:ear_pain", to: "question:hearing_change", relation: "asks", weight: 0.8 },

    { id: "e70", from: "complaint:breathlessness", to: "skill:red_flag_detection", relation: "requires", weight: 1 },
    { id: "e71", from: "complaint:breathlessness", to: "skill:respiratory_failure", relation: "requires", weight: 1 },
    { id: "e72", from: "complaint:breathlessness", to: "protocol:respiratory_emergency", relation: "governed_by", weight: 1 },
    { id: "e73", from: "complaint:breathlessness", to: "diagnosis:asthma_exacerbation", relation: "suggests", weight: 0.6 },
    { id: "e74", from: "complaint:breathlessness", to: "question:sob", relation: "asks", weight: 1 },

    { id: "e18", from: "skill:red_flag_detection", to: "engine:redFlagEngine", relation: "handled_by", weight: 1 },
    { id: "e19", from: "skill:pneumonia_risk", to: "engine:bayesianDifferentialEngine", relation: "handled_by", weight: 0.9 },
    { id: "e19b", from: "skill:mi_risk", to: "engine:bayesianDifferentialEngine", relation: "handled_by", weight: 0.9 },
    { id: "e19c", from: "skill:sah_risk", to: "engine:bayesianDifferentialEngine", relation: "handled_by", weight: 0.85 },
    { id: "e19d", from: "skill:stroke_risk", to: "engine:temporalRiskEngine", relation: "handled_by", weight: 0.9 },
    { id: "e19e", from: "skill:sepsis_risk", to: "engine:clusterScoringEngine", relation: "handled_by", weight: 0.85 },
    { id: "e19f", from: "skill:peritonsillar_abscess", to: "engine:redFlagEngine", relation: "handled_by", weight: 0.9 },
    { id: "e19g", from: "skill:mastoiditis", to: "engine:redFlagEngine", relation: "handled_by", weight: 0.85 },
    { id: "e19h", from: "skill:respiratory_failure", to: "engine:temporalRiskEngine", relation: "handled_by", weight: 0.9 },
    { id: "e19i", from: "skill:pe_risk", to: "engine:bayesianDifferentialEngine", relation: "handled_by", weight: 0.8 },

    { id: "e20", from: "question:duration", to: "engine:nextQuestionSelector", relation: "supports", weight: 0.7 },
    { id: "e20b", from: "question:fever", to: "engine:nextQuestionSelector", relation: "supports", weight: 0.8 },
    { id: "e20c", from: "question:sob", to: "engine:nextQuestionSelector", relation: "supports", weight: 0.9 },
    { id: "e21", from: "protocol:cdc_respiratory", to: "engine:protocolSelectionEngine", relation: "handled_by", weight: 1 },
    { id: "e21b", from: "protocol:acep_aha_chest_pain", to: "engine:protocolSelectionEngine", relation: "handled_by", weight: 1 },
    { id: "e21c", from: "protocol:headache_emergency", to: "engine:protocolSelectionEngine", relation: "handled_by", weight: 1 },

    { id: "e22", from: "diagnosis:viral_uri", to: "disposition:self_care", relation: "can_lead_to", weight: 0.7 },
    { id: "e23", from: "diagnosis:pneumonia", to: "disposition:urgent_care", relation: "can_lead_to", weight: 0.8 },
    { id: "e24", from: "diagnosis:acs", to: "disposition:er_now", relation: "can_lead_to", weight: 1 },
    { id: "e25", from: "diagnosis:sah", to: "disposition:er_now", relation: "can_lead_to", weight: 1 },
    { id: "e25b", from: "diagnosis:aortic_dissection", to: "disposition:er_now", relation: "can_lead_to", weight: 1 },
    { id: "e25c", from: "diagnosis:stroke", to: "disposition:er_now", relation: "can_lead_to", weight: 1 },
    { id: "e25d", from: "diagnosis:meningitis", to: "disposition:er_now", relation: "can_lead_to", weight: 0.95 },
    { id: "e25e", from: "diagnosis:bppv", to: "disposition:urgent_care", relation: "can_lead_to", weight: 0.6 },
    { id: "e25f", from: "diagnosis:strep_pharyngitis", to: "disposition:urgent_care", relation: "can_lead_to", weight: 0.7 },
    { id: "e25g", from: "diagnosis:peritonsillar_abscess_dx", to: "disposition:er_now", relation: "can_lead_to", weight: 0.95 },
    { id: "e25h", from: "diagnosis:otitis_media", to: "disposition:urgent_care", relation: "can_lead_to", weight: 0.6 },
    { id: "e25i", from: "diagnosis:mastoiditis_dx", to: "disposition:er_now", relation: "can_lead_to", weight: 0.9 },
    { id: "e25j", from: "diagnosis:asthma_exacerbation", to: "disposition:urgent_care", relation: "can_lead_to", weight: 0.7 },
    { id: "e25k", from: "diagnosis:meningococcemia", to: "disposition:er_now", relation: "can_lead_to", weight: 1 },

    { id: "e26", from: "symptom:sob", to: "disposition:er_now", relation: "escalates_to", weight: 0.85 },
    { id: "e27", from: "symptom:worst_headache", to: "disposition:er_now", relation: "escalates_to", weight: 0.95 },
    { id: "e28", from: "symptom:diaphoresis", to: "disposition:er_now", relation: "escalates_to", weight: 0.9 },
    { id: "e29", from: "symptom:tearing_pain", to: "disposition:er_now", relation: "escalates_to", weight: 0.95 },
    { id: "e29b", from: "symptom:trismus", to: "disposition:er_now", relation: "escalates_to", weight: 0.9 },
    { id: "e29c", from: "symptom:stridor", to: "disposition:er_now", relation: "escalates_to", weight: 0.95 },
    { id: "e29d", from: "symptom:petechiae", to: "disposition:er_now", relation: "escalates_to", weight: 0.95 },
    { id: "e29e", from: "symptom:mastoid_tenderness", to: "disposition:er_now", relation: "escalates_to", weight: 0.9 },
    { id: "e29f", from: "symptom:unilateral_weakness", to: "disposition:er_now", relation: "escalates_to", weight: 0.95 },
  ],
};
