import type { SymptomPackRow, ModifierPackRow, ClinicianAlgorithmRow } from "../../../shared/packRows";
import type { PackQuestionRow } from "../../../shared/packQuestionRows";

export const endocrinologyFullSymptomPackRows: SymptomPackRow[] = [
  { id: "endo_hyperglycemia", system: "endocrinology", tier: "symptom", title: "High Blood Sugar Concern", isActive: true, version: 2, aliases: ["high blood sugar", "hyperglycemia"], likelyDisposition: "telemed_now", questionsJson: "[]", redFlags: ["vomiting", "confusion"], autoEscalateRules: ["vomiting=yes", "confusion=yes"], autoReviewRules: ["ketones=yes"], planTemplateKey: "endo_hyperglycemia" },
  { id: "endo_hypoglycemia", system: "endocrinology", tier: "symptom", title: "Low Blood Sugar Concern", isActive: true, version: 2, aliases: ["low blood sugar", "hypoglycemia"], likelyDisposition: "telemed_now", questionsJson: "[]", redFlags: ["confusion", "passed_out"], autoEscalateRules: ["confusion=yes", "passed_out=yes"], autoReviewRules: ["recurrent=yes"], planTemplateKey: "endo_hypoglycemia" },
  { id: "endo_thyroid_symptoms", system: "endocrinology", tier: "symptom", title: "Thyroid Symptoms", isActive: true, version: 2, aliases: ["thyroid problem"], likelyDisposition: "office_followup", questionsJson: "[]", redFlags: ["chest_pain", "sob"], autoEscalateRules: ["chest_pain=yes", "sob=yes"], autoReviewRules: ["weight_loss=yes", "palpitations=yes"], planTemplateKey: "endo_thyroid_symptoms" },
  { id: "endo_adrenal_concern", system: "endocrinology", tier: "symptom", title: "Adrenal Crisis Concern", isActive: true, version: 2, aliases: ["adrenal problem", "adrenal crisis"], likelyDisposition: "er_now", questionsJson: "[]", redFlags: ["fainting", "vomiting"], autoEscalateRules: ["fainting=yes", "vomiting=yes"], autoReviewRules: [], planTemplateKey: "endo_adrenal_concern" },
  { id: "endo_polyuria_polydipsia", system: "endocrinology", tier: "symptom", title: "Excessive Thirst / Urination", isActive: true, version: 2, aliases: ["excessive thirst", "peeing a lot"], likelyDisposition: "office_followup", questionsJson: "[]", redFlags: ["confusion"], autoEscalateRules: ["confusion=yes"], autoReviewRules: ["weight_loss=yes", "known_diabetes=yes"], planTemplateKey: "endo_polyuria_polydipsia" },
  { id: "endo_goiter_neck_mass", system: "endocrinology", tier: "symptom", title: "Goiter / Thyroid Neck Mass", isActive: true, version: 1, aliases: ["goiter", "thyroid swelling"], likelyDisposition: "office_followup", questionsJson: "[]", redFlags: ["trouble_swallowing", "breathing"], autoEscalateRules: ["breathing=yes"], autoReviewRules: ["trouble_swallowing=yes", "rapid_growth=yes"], planTemplateKey: "endo_goiter_neck_mass" },
  { id: "endo_diabetes_med_issue", system: "endocrinology", tier: "symptom", title: "Diabetes Medication Issue", isActive: true, version: 1, aliases: ["insulin issue", "diabetes medicine issue"], likelyDisposition: "telemed_now", questionsJson: "[]", redFlags: ["passed_out", "confusion"], autoEscalateRules: ["passed_out=yes", "confusion=yes"], autoReviewRules: ["recurrent=yes"], planTemplateKey: "endo_diabetes_med_issue" },
  { id: "endo_cushing_like", system: "endocrinology", tier: "symptom", title: "Cushing-like Symptoms", isActive: true, version: 1, aliases: ["cushing symptoms", "steroid weight gain"], likelyDisposition: "office_followup", questionsJson: "[]", redFlags: [], autoEscalateRules: [], autoReviewRules: ["steroid_use=yes"], planTemplateKey: "endo_cushing_like" },
];

export const endocrinologyFullQuestionRows: PackQuestionRow[] = [
  { id: "pq_endo_hyper_1", packId: "endo_hyperglycemia", questionId: "vomiting", prompt: "Any vomiting?", type: "yes_no", priority: 1, required: false, isActive: true, version: 1 },
  { id: "pq_endo_hyper_2", packId: "endo_hyperglycemia", questionId: "confusion", prompt: "Any confusion?", type: "yes_no", priority: 2, required: false, isActive: true, version: 1 },
  { id: "pq_endo_hyper_3", packId: "endo_hyperglycemia", questionId: "ketones", prompt: "Ketones present or suspected?", type: "yes_no", priority: 3, required: false, isActive: true, version: 1 },
  { id: "pq_endo_hypo_1", packId: "endo_hypoglycemia", questionId: "confusion", prompt: "Any confusion?", type: "yes_no", priority: 1, required: false, isActive: true, version: 1 },
  { id: "pq_endo_hypo_2", packId: "endo_hypoglycemia", questionId: "passed_out", prompt: "Passed out?", type: "yes_no", priority: 2, required: false, isActive: true, version: 1 },
  { id: "pq_endo_hypo_3", packId: "endo_hypoglycemia", questionId: "recurrent", prompt: "Happening repeatedly?", type: "yes_no", priority: 3, required: false, isActive: true, version: 1 },
  { id: "pq_endo_thyr_1", packId: "endo_thyroid_symptoms", questionId: "palpitations", prompt: "Any palpitations?", type: "yes_no", priority: 1, required: false, isActive: true, version: 1 },
  { id: "pq_endo_thyr_2", packId: "endo_thyroid_symptoms", questionId: "weight_loss", prompt: "Any weight loss?", type: "yes_no", priority: 2, required: false, isActive: true, version: 1 },
  { id: "pq_endo_thyr_3", packId: "endo_thyroid_symptoms", questionId: "chest_pain", prompt: "Any chest pain?", type: "yes_no", priority: 3, required: false, isActive: true, version: 1 },
  { id: "pq_endo_thyr_4", packId: "endo_thyroid_symptoms", questionId: "sob", prompt: "Any shortness of breath?", type: "yes_no", priority: 4, required: false, isActive: true, version: 1 },
];

export const endocrinologyFullModifierRows: ModifierPackRow[] = [
  { id: "endo_mod_known_diabetes", system: "endocrinology", tier: "modifier", title: "Known Diabetes", isActive: true, version: 2, appliesToSymptoms: ["endo_hyperglycemia", "endo_hypoglycemia", "endo_polyuria_polydipsia", "endo_diabetes_med_issue"], triggers: ["known_diabetes=yes"], riskAdjustmentsJson: JSON.stringify([{ condition: "known_diabetes=yes", action: "raise_risk", amount: 10, reason: "Known diabetes increases acute glycemic risk" }]) },
  { id: "endo_mod_steroid_use", system: "endocrinology", tier: "modifier", title: "Chronic Steroid Use", isActive: true, version: 2, appliesToSymptoms: ["endo_adrenal_concern", "endo_cushing_like"], triggers: ["steroid_use=yes"], riskAdjustmentsJson: JSON.stringify([{ condition: "steroid_use=yes", action: "raise_risk", amount: 20, reason: "Adrenal suppression risk" }, { condition: "steroid_use=yes AND vomiting=yes", action: "force_escalation", reason: "Possible adrenal crisis" }]) },
];

export const endocrinologyFullAlgorithmRows: ClinicianAlgorithmRow[] = [
  { id: "endo_algo_dka_hhs_screen", system: "endocrinology", tier: "clinician_algorithm", title: "DKA/HHS Screen", isActive: true, version: 2, entryCriteria: ["vomiting=yes", "confusion=yes", "ketones=yes"], requiredInputs: ["vomiting", "confusion", "ketones"], outputActions: ["flag DKA/HHS concern", "recommend urgent emergency evaluation"] },
  { id: "endo_algo_adrenal_crisis_screen", system: "endocrinology", tier: "clinician_algorithm", title: "Adrenal Crisis Screen", isActive: true, version: 2, entryCriteria: ["fainting=yes", "vomiting=yes AND steroid_use=yes"], requiredInputs: ["fainting", "vomiting", "steroid_use"], outputActions: ["flag adrenal crisis concern", "recommend emergency evaluation"] },
  { id: "endo_algo_thyrotoxicosis_screen", system: "endocrinology", tier: "clinician_algorithm", title: "Thyrotoxicosis Screen", isActive: true, version: 1, entryCriteria: ["palpitations=yes AND weight_loss=yes", "chest_pain=yes AND palpitations=yes"], requiredInputs: ["palpitations", "weight_loss", "chest_pain", "sob"], outputActions: ["flag possible severe hyperthyroid pattern", "recommend urgent evaluation if unstable features present"] },
];
