import type { SymptomPackRow, ModifierPackRow, ClinicianAlgorithmRow } from '../../../shared/packRows';
import type { PackQuestionRow } from '../../../shared/packQuestionRows';

export const endocrinologyExpansionSymptomPackRows: SymptomPackRow[] = [
  { id: 'endo_hyperglycemia', system: 'endocrinology', tier: 'symptom', title: 'High Blood Sugar Concern', isActive: true, version: 2, aliases: ['high blood sugar', 'hyperglycemia'], likelyDisposition: 'telemed_now', questionsJson: '[]', redFlags: ['vomiting', 'confusion'], autoEscalateRules: ['vomiting=yes', 'confusion=yes'], autoReviewRules: ['ketones=yes'], planTemplateKey: 'endo_hyperglycemia' },
  { id: 'endo_hypoglycemia', system: 'endocrinology', tier: 'symptom', title: 'Low Blood Sugar Concern', isActive: true, version: 2, aliases: ['low blood sugar', 'hypoglycemia'], likelyDisposition: 'telemed_now', questionsJson: '[]', redFlags: ['confusion', 'passed_out'], autoEscalateRules: ['confusion=yes', 'passed_out=yes'], autoReviewRules: ['recurrent=yes'], planTemplateKey: 'endo_hypoglycemia' },
  { id: 'endo_thyroid_symptoms', system: 'endocrinology', tier: 'symptom', title: 'Thyroid Symptoms', isActive: true, version: 2, aliases: ['thyroid problem', 'hyperthyroid', 'hypothyroid'], likelyDisposition: 'office_followup', questionsJson: '[]', redFlags: ['chest_pain', 'sob'], autoEscalateRules: ['chest_pain=yes', 'sob=yes'], autoReviewRules: ['weight_loss=yes', 'palpitations=yes'], planTemplateKey: 'endo_thyroid_symptoms' },
  { id: 'endo_adrenal_concern', system: 'endocrinology', tier: 'symptom', title: 'Adrenal Crisis Concern', isActive: true, version: 2, aliases: ['adrenal problem', 'adrenal crisis'], likelyDisposition: 'er_now', questionsJson: '[]', redFlags: ['fainting', 'vomiting'], autoEscalateRules: ['fainting=yes', 'vomiting=yes'], autoReviewRules: [], planTemplateKey: 'endo_adrenal_concern' },
  { id: 'endo_polyuria_polydipsia', system: 'endocrinology', tier: 'symptom', title: 'Excessive Thirst / Urination', isActive: true, version: 2, aliases: ['excessive thirst', 'peeing a lot', 'polyuria', 'polydipsia'], likelyDisposition: 'office_followup', questionsJson: '[]', redFlags: ['confusion'], autoEscalateRules: ['confusion=yes'], autoReviewRules: ['weight_loss=yes', 'known_diabetes=yes'], planTemplateKey: 'endo_polyuria_polydipsia' },
  { id: 'endo_goiter_neck_mass', system: 'endocrinology', tier: 'symptom', title: 'Goiter / Thyroid Neck Mass', isActive: true, version: 1, aliases: ['goiter', 'thyroid swelling'], likelyDisposition: 'office_followup', questionsJson: '[]', redFlags: ['breathing', 'trouble_swallowing'], autoEscalateRules: ['breathing=yes', 'trouble_swallowing=yes'], autoReviewRules: ['rapid_growth=yes'], planTemplateKey: 'endo_goiter_neck_mass' },
  { id: 'endo_menstrual_hormonal', system: 'endocrinology', tier: 'symptom', title: 'Hormonal / Menstrual Endocrine Concern', isActive: true, version: 1, aliases: ['irregular periods endocrine', 'pcos concern'], likelyDisposition: 'office_followup', questionsJson: '[]', redFlags: [], autoEscalateRules: [], autoReviewRules: ['pregnancy=yes', 'heavy_bleeding=yes'], planTemplateKey: 'endo_menstrual_hormonal' },
  { id: 'endo_pituitary_concern', system: 'endocrinology', tier: 'symptom', title: 'Pituitary / Hormonal Headache-Vision Concern', isActive: true, version: 1, aliases: ['pituitary problem'], likelyDisposition: 'telemed_now', questionsJson: '[]', redFlags: ['vision', 'severe_headache'], autoEscalateRules: ['vision=yes AND severe_headache=yes'], autoReviewRules: ['galactorrhea=yes'], planTemplateKey: 'endo_pituitary_concern' },
];

export const endocrinologyExpansionQuestionRows: PackQuestionRow[] = [
  { id: 'pq_endo_hyper_1', packId: 'endo_hyperglycemia', questionId: 'vomiting', prompt: 'Any vomiting?', type: 'yes_no', priority: 1, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_hyper_2', packId: 'endo_hyperglycemia', questionId: 'confusion', prompt: 'Any confusion?', type: 'yes_no', priority: 2, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_hyper_3', packId: 'endo_hyperglycemia', questionId: 'ketones', prompt: 'Ketones present or suspected?', type: 'yes_no', priority: 3, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_hypo_1', packId: 'endo_hypoglycemia', questionId: 'confusion', prompt: 'Any confusion?', type: 'yes_no', priority: 1, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_hypo_2', packId: 'endo_hypoglycemia', questionId: 'passed_out', prompt: 'Passed out?', type: 'yes_no', priority: 2, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_thy_1', packId: 'endo_thyroid_symptoms', questionId: 'palpitations', prompt: 'Palpitations or racing heart?', type: 'yes_no', priority: 1, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_thy_2', packId: 'endo_thyroid_symptoms', questionId: 'weight_loss', prompt: 'Unexpected weight loss?', type: 'yes_no', priority: 2, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_goiter_1', packId: 'endo_goiter_neck_mass', questionId: 'breathing', prompt: 'Any breathing trouble?', type: 'yes_no', priority: 1, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_goiter_2', packId: 'endo_goiter_neck_mass', questionId: 'trouble_swallowing', prompt: 'Any trouble swallowing?', type: 'yes_no', priority: 2, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_pit_1', packId: 'endo_pituitary_concern', questionId: 'vision', prompt: 'Any vision change?', type: 'yes_no', priority: 1, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_pit_2', packId: 'endo_pituitary_concern', questionId: 'severe_headache', prompt: 'Any severe headache?', type: 'yes_no', priority: 2, required: false, isActive: true, version: 1 },
  { id: 'pq_endo_pit_3', packId: 'endo_pituitary_concern', questionId: 'galactorrhea', prompt: 'Unexpected breast milk discharge?', type: 'yes_no', priority: 3, required: false, isActive: true, version: 1 },
];

export const endocrinologyExpansionModifierRows: ModifierPackRow[] = [
  { id: 'endo_mod_known_diabetes', system: 'endocrinology', tier: 'modifier', title: 'Known Diabetes', isActive: true, version: 2, appliesToSymptoms: ['endo_hyperglycemia', 'endo_hypoglycemia', 'endo_polyuria_polydipsia'], triggers: ['known_diabetes=yes'], riskAdjustmentsJson: JSON.stringify([{ condition: 'known_diabetes=yes', action: 'raise_risk', amount: 10, reason: 'Known diabetes increases acute glycemic risk' }]) },
  { id: 'endo_mod_steroid_use', system: 'endocrinology', tier: 'modifier', title: 'Chronic Steroid Use', isActive: true, version: 2, appliesToSymptoms: ['endo_adrenal_concern'], triggers: ['steroid_use=yes'], riskAdjustmentsJson: JSON.stringify([{ condition: 'steroid_use=yes', action: 'raise_risk', amount: 20, reason: 'Adrenal suppression risk' }, { condition: 'steroid_use=yes AND vomiting=yes', action: 'force_escalation', reason: 'Possible adrenal crisis' }]) },
  { id: 'endo_mod_pregnancy', system: 'endocrinology', tier: 'modifier', title: 'Pregnancy', isActive: true, version: 1, appliesToSymptoms: ['endo_hyperglycemia', 'endo_hypoglycemia', 'endo_thyroid_symptoms', 'endo_menstrual_hormonal'], triggers: ['pregnancy=yes'], riskAdjustmentsJson: JSON.stringify([{ condition: 'pregnancy=yes', action: 'force_review', reason: 'Pregnancy changes endocrine thresholds' }]) },
];

export const endocrinologyExpansionAlgorithmRows: ClinicianAlgorithmRow[] = [
  { id: 'endo_algo_dka_hhs_screen', system: 'endocrinology', tier: 'clinician_algorithm', title: 'DKA/HHS Screen', isActive: true, version: 2, entryCriteria: ['vomiting=yes', 'confusion=yes', 'ketones=yes'], requiredInputs: ['vomiting', 'confusion', 'ketones'], outputActions: ['flag DKA/HHS concern', 'recommend urgent emergency evaluation'] },
  { id: 'endo_algo_adrenal_crisis_screen', system: 'endocrinology', tier: 'clinician_algorithm', title: 'Adrenal Crisis Screen', isActive: true, version: 2, entryCriteria: ['fainting=yes', 'vomiting=yes AND steroid_use=yes'], requiredInputs: ['fainting', 'vomiting', 'steroid_use'], outputActions: ['flag adrenal crisis concern', 'recommend emergency evaluation'] },
  { id: 'endo_algo_pituitary_mass_screen', system: 'endocrinology', tier: 'clinician_algorithm', title: 'Pituitary Mass Screen', isActive: true, version: 1, entryCriteria: ['vision=yes AND severe_headache=yes', 'galactorrhea=yes AND severe_headache=yes'], requiredInputs: ['vision', 'severe_headache', 'galactorrhea'], outputActions: ['flag pituitary mass concern', 'recommend urgent imaging / specialist evaluation'] },
];
