/**
 * R004 — Structured Clinical Question Sequences
 *
 * Questions are hardcoded per complaint — never generated by LLM.
 * Questions follow clinical priority order:
 *   1. Characterization (onset, duration, severity)
 *   2. Safety red flags (dyspnea, neuro deficits, blood)
 *   3. Associated symptoms
 *   4. History / risk factors
 *
 * All 18 complaint clusters have ≥4 questions.
 *
 * Usage:
 *   getNextQuestion("headache", 0)       → "How long have you had the headache?"
 *   getNextQuestion("headache", 1)       → "On a scale of 1–10, how bad is the pain?"
 *   getNextQuestion("nausea_vomiting", 0) → "How long have you been nauseated?"
 *   getNextQuestion("abdominal_pain", 3) → "Any fever?"
 */

const SEQUENCES: Record<string, readonly string[]> = {

  // ── Headache ──────────────────────────────────────────────────────────────
  headache: [
    "How long have you had the headache?",
    "On a scale of 1–10, how bad is the pain?",
    "Is this the worst headache of your life?",
    "Any stiff neck or sensitivity to light?",
    "Any fever, body aches, or runny nose with it?",
  ],

  // ── Nausea / Vomiting ─────────────────────────────────────────────────────
  nausea_vomiting: [
    "How long have you been nauseated?",
    "Have you vomited, and if so how many times?",
    "Any blood in the vomit?",
    "Any abdominal pain with it?",
    "Any fever, chills, or body aches?",
    "Are you able to keep fluids down?",
    "Any dizziness or feeling faint?",
  ],

  // ── Abdominal Pain ────────────────────────────────────────────────────────
  abdominal_pain: [
    "Where exactly is the pain — upper, lower, or all over?",
    "How long have you had it?",
    "On a scale of 1–10, how bad is the pain?",
    "Any fever?",
    "Any nausea or vomiting?",
    "Any blood in your stool or black tarry stools?",
    "Any pain or burning with urination?",
  ],

  // ── Chest Pain ────────────────────────────────────────────────────────────
  chest_pain: [
    "Can you describe the pain — sharp, pressure, or squeezing?",
    "When did it start?",
    "Does it spread to your arm, jaw, or back?",
    "Any sweating or feeling clammy?",
    "Any shortness of breath with it?",
    "Is the pain worse when you press on your chest?",
    "Any prior heart problems?",
  ],

  // ── Shortness of Breath ───────────────────────────────────────────────────
  shortness_of_breath: [
    "How long have you been having trouble breathing?",
    "Is it constant or does it come and go?",
    "Any chest pain or tightness with it?",
    "Any fever or cough?",
    "Can you speak in full sentences comfortably?",
    "Any history of asthma, COPD, or heart problems?",
  ],

  // ── Sore Throat ───────────────────────────────────────────────────────────
  sore_throat: [
    "How long have you had the sore throat?",
    "On a scale of 1–10, how bad?",
    "Any fever?",
    "Any white patches or pus on your tonsils?",
    "Any trouble swallowing your own saliva?",
    "Any body aches, cough, or runny nose?",
    "Any trouble breathing?",
  ],

  // ── Cough ─────────────────────────────────────────────────────────────────
  cough: [
    "How long have you had the cough?",
    "Any fever, body aches, or fatigue?",
    "Any trouble breathing or shortness of breath?",
    "What does the phlegm look like — clear, yellow, or green?",
    "Any smoking history or lung conditions?",
    "How old are you?",
  ],

  // ── UTI / Urinary Symptoms ────────────────────────────────────────────────
  uti: [
    "How long have you had the burning with urination?",
    "Any fever?",
    "Any pain in your back or side?",
    "Any blood in your urine?",
    "Are you pregnant, or could you be?",
    "Any nausea or vomiting?",
  ],

  // ── Upper Respiratory / Sinus ─────────────────────────────────────────────
  uri_sinus: [
    "How long have you had the congestion or sinus symptoms?",
    "Any fever?",
    "Any facial pain or pressure around your cheeks or forehead?",
    "Is the mucus clear, yellow, or green?",
    "Any headache or ear pain with it?",
    "Any trouble breathing through your nose?",
  ],

  // ── Back Pain ─────────────────────────────────────────────────────────────
  back_pain: [
    "Which part of your back — neck area, mid, or low back?",
    "How long have you had it?",
    "On a scale of 1–10, how bad is the pain?",
    "Any numbness or weakness in your legs?",
    "Any trouble controlling your bowels or urine?",
    "Any fever?",
    "Did this start after an injury or heavy lifting?",
  ],

  // ── Fever ─────────────────────────────────────────────────────────────────
  fever: [
    "How long have you had the fever?",
    "What is your temperature, if you know it?",
    "Any chills, body aches, or muscle pain?",
    "Any sore throat, cough, or runny nose?",
    "Any rash?",
    "Any confusion or unusual mental changes?",
  ],

  // ── Rash ──────────────────────────────────────────────────────────────────
  rash: [
    "How long have you had the rash?",
    "Where on your body is it?",
    "Is it itchy, painful, or blistering?",
    "Any fever with it?",
    "Any difficulty breathing or throat tightness?",
    "Any new medications, foods, or exposures recently?",
  ],

  // ── Dizziness ─────────────────────────────────────────────────────────────
  dizziness: [
    "Is it more of a spinning sensation or a lightheaded feeling?",
    "How long does each episode last?",
    "Any fainting or near-fainting?",
    "Any weakness, numbness, or speech changes?",
    "Any hearing changes or ringing in your ears?",
    "Any nausea with it?",
  ],

  // ── Ear Pain ──────────────────────────────────────────────────────────────
  ear_pain: [
    "How long have you had the ear pain?",
    "Is it one ear or both?",
    "Any fever?",
    "Any discharge or fluid coming from the ear?",
    "Any hearing loss with it?",
    "Any recent cold or upper respiratory symptoms?",
  ],

  // ── Eye Complaint ─────────────────────────────────────────────────────────
  eye_complaint: [
    "How long have you had the eye problem?",
    "Which eye — left, right, or both?",
    "Any pain, or just redness or discharge?",
    "Any change in your vision?",
    "Any trauma or something in your eye?",
    "Any fever or other symptoms?",
  ],

  // ── Anxiety / Panic ───────────────────────────────────────────────────────
  anxiety: [
    "How long have you been feeling this way?",
    "Any chest pain or shortness of breath with it?",
    "Any racing heartbeat?",
    "Are you having any thoughts of harming yourself?",
    "Any prior panic attacks or anxiety?",
    "Any recent major stressors?",
  ],

  // ── Laceration / Cut ──────────────────────────────────────────────────────
  laceration: [
    "Where is the cut?",
    "How did it happen?",
    "Is the bleeding still active or has it slowed down?",
    "How deep does the cut look?",
    "Any numbness near the cut?",
    "Are you up to date on tetanus?",
  ],

  // ── Palpitations ─────────────────────────────────────────────────────────
  palpitations: [
    "How long have you been feeling your heart racing or pounding?",
    "Any chest pain or pressure with it?",
    "Any dizziness, lightheadedness, or fainting?",
    "Any shortness of breath?",
    "Any prior heart problems or irregular heart rhythm?",
    "Does it come and go or is it constant?",
  ],
};

// Fallback for unmapped or "unknown" complaints
const DEFAULT_QUESTIONS: readonly string[] = [
  "How long have you been having these symptoms?",
  "On a scale of 1–10, how bad is it?",
  "Any fever?",
  "Any trouble breathing?",
  "Any other symptoms you are worried about?",
];

/**
 * F020 — Field-hint map: parallel to SEQUENCES.
 * Each entry is the extractedFields key the question covers, or null (always ask).
 * If the field is already populated in extractedFields, the question is skipped.
 */
const QUESTION_FIELD_HINTS: Record<string, readonly (string | null)[]> = {
  headache:         ["duration", "severity", "thunderclap", "stiff_neck", "fever"],
  nausea_vomiting:  ["duration", "vomiting", null, null, "fever", null, "dizziness"],
  abdominal_pain:   [null, "duration", "severity", "fever", "nausea", null, null],
  chest_pain:       [null, "duration", "radiation", "diaphoresis", "dyspnea", null, null],
  shortness_of_breath: ["duration", null, null, "fever", null, null],
  sore_throat:      ["duration", "severity", "fever", null, null, null, "dyspnea"],
  cough:            ["duration", "fever", "dyspnea", null, null, "age"],
  uti:              ["duration", "fever", null, null, null, "vomiting"],
  uri_sinus:        ["duration", "fever", null, null, null, "rhinorrhea"],
  back_pain:        [null, "duration", "severity", null, null, "fever", null],
  fever:            ["duration", null, "chills", null, null, null],
  rash:             ["duration", null, null, "fever", "dyspnea", null],
  dizziness:        [null, "duration", null, null, null, "nausea"],
  ear_pain:         ["duration", null, "fever", null, null, null],
  eye_complaint:    ["duration", null, null, null, null, "fever"],
  anxiety:          ["duration", "dyspnea", null, null, null, null],
  laceration:       [null, null, null, null, null, null],
  palpitations:     ["duration", null, "dizziness", "dyspnea", null, null],
};

/**
 * Return the question at the given zero-based index for a complaint.
 * Returns empty string when the sequence is exhausted.
 *
 * @param complaint  complaint code (e.g. "headache", "nausea_vomiting")
 * @param index      zero-based question index
 */
export function getNextQuestion(complaint: string, index: number): string {
  const seq = SEQUENCES[complaint] ?? DEFAULT_QUESTIONS;
  return seq[index] ?? "";
}

/**
 * F020 — Gap-aware question selector.
 *
 * Scans forward from `fromIndex`, skipping any question whose field is already
 * populated in `extractedFields`. Returns the first unanswered question and the
 * index to store as `session.questionIndex` for the next turn.
 *
 * Returns null when all scripted questions are exhausted (caller should switch
 * to the GPT phase immediately).
 *
 * @param complaint       routerCode (e.g. "cough", "nausea_vomiting")
 * @param extractedFields semantic fields collected so far
 * @param fromIndex       where to start scanning (= current session.questionIndex)
 */
export function getNextGapQuestion(
  complaint: string,
  extractedFields: Record<string, any>,
  fromIndex: number,
): { question: string; nextIndex: number } | null {
  const seq   = SEQUENCES[complaint] ?? DEFAULT_QUESTIONS;
  const hints = QUESTION_FIELD_HINTS[complaint] ?? null;

  for (let i = fromIndex; i < seq.length; i++) {
    const field = hints?.[i] ?? null;
    const alreadyAnswered =
      field !== null &&
      extractedFields[field] !== undefined &&
      extractedFields[field] !== null;
    if (!alreadyAnswered) {
      return { question: seq[i], nextIndex: i + 1 };
    }
  }
  return null; // all scripted questions answered — caller should go to GPT phase
}

/**
 * Total number of questions defined for a complaint.
 */
export function getQuestionCount(complaint: string): number {
  return (SEQUENCES[complaint] ?? DEFAULT_QUESTIONS).length;
}

/**
 * All questions for a complaint (for reference / debugging).
 */
export function getAllQuestions(complaint: string): readonly string[] {
  return SEQUENCES[complaint] ?? DEFAULT_QUESTIONS;
}

/**
 * Minimum number of questions to ask before computing disposition (R005 hard stop).
 */
export const MIN_QUESTIONS_BEFORE_DISPOSITION = 4;
