import { ReasoningGraphNode } from "../skills/shared/skillTypes";

export const GRAPH_NODES: ReasoningGraphNode[] = [
  {
    skillName: "collect_modifiers",
    category: "intake",
    produces: ["modifiers"],
    safetyClass: "high",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 2,
    engineType: "rules",
  },
  {
    skillName: "extract_med_to_condition_triggers",
    category: "intake",
    produces: ["med_condition_triggers"],
    safetyClass: "high",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 2,
    engineType: "rules",
  },
  {
    skillName: "identify_chief_complaint",
    category: "intake",
    produces: ["complaint_id"],
    safetyClass: "high",
    estimatedCostUsd: 0.0001,
    estimatedLatencyMs: 10,
    engineType: "hybrid",
  },
  {
    skillName: "normalize_patient_story",
    category: "intake",
    produces: ["structured_facts"],
    safetyClass: "high",
    estimatedCostUsd: 0.0001,
    estimatedLatencyMs: 8,
    engineType: "hybrid",
  },
  {
    skillName: "detect_red_flags",
    category: "safety",
    produces: ["red_flags", "red_flag_severity"],
    safetyClass: "critical",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 4,
    engineType: "rules",
  },
  {
    skillName: "run_complaint_question_bundle",
    category: "questions",
    produces: ["pending_questions"],
    safetyClass: "high",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 3,
    engineType: "rules",
  },
  {
    skillName: "trigger_global_secondary_questions",
    category: "questions",
    produces: ["global_question_bundles"],
    safetyClass: "high",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 3,
    engineType: "rules",
  },
  {
    skillName: "select_next_best_question",
    category: "questions",
    produces: ["next_question"],
    safetyClass: "high",
    estimatedCostUsd: 0.00005,
    estimatedLatencyMs: 4,
    engineType: "hybrid",
  },
  {
    skillName: "score_differential_clusters",
    category: "reasoning",
    produces: ["scored_clusters"],
    safetyClass: "high",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 4,
    engineType: "rules",
  },
  {
    skillName: "apply_clinical_score",
    category: "reasoning",
    produces: ["clinical_score"],
    safetyClass: "critical",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 2,
    engineType: "rules",
  },
  {
    skillName: "generate_differential",
    category: "reasoning",
    produces: ["differential"],
    safetyClass: "high",
    estimatedCostUsd: 0.00005,
    estimatedLatencyMs: 5,
    engineType: "hybrid",
  },
  {
    skillName: "check_consistency_and_gaps",
    category: "audit",
    produces: ["inconsistencies", "missing_critical_data"],
    safetyClass: "high",
    estimatedCostUsd: 0.00005,
    estimatedLatencyMs: 5,
    engineType: "hybrid",
  },
  {
    skillName: "determine_disposition",
    category: "safety",
    produces: ["disposition"],
    safetyClass: "critical",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 3,
    engineType: "rules",
  },
  {
    skillName: "generate_emergency_warning",
    category: "output",
    produces: ["warning_block"],
    safetyClass: "critical",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 2,
    engineType: "rules",
  },
  {
    skillName: "generate_assessment_plan",
    category: "output",
    produces: ["assessment_plan"],
    safetyClass: "high",
    estimatedCostUsd: 0.00005,
    estimatedLatencyMs: 5,
    engineType: "hybrid",
  },
  {
    skillName: "generate_physician_review_packet",
    category: "output",
    produces: ["review_packet"],
    safetyClass: "critical",
    estimatedCostUsd: 0.00005,
    estimatedLatencyMs: 5,
    engineType: "hybrid",
  },
  {
    skillName: "attach_outcome_stub",
    category: "outcomes",
    produces: ["outcome_stub"],
    safetyClass: "high",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 1,
    engineType: "rules",
  },
  {
    skillName: "measure_workflow_value",
    category: "analytics",
    produces: ["workflow_value"],
    safetyClass: "medium",
    estimatedCostUsd: 0,
    estimatedLatencyMs: 1,
    engineType: "rules",
  },
];

export function getGraphNode(skillName: string) {
  return GRAPH_NODES.find((n) => n.skillName === skillName);
}
