export const COMPLAINTS: string[] = [
  // ENT
  "sore_throat", "ear_pain", "sinus_pressure", "hoarseness", "epistaxis",
  "nasal_congestion", "tinnitus", "hearing_loss", "stridor", "neck_mass",
  "peritonsillar_abscess", "foreign_body_ear", "foreign_body_nose", "vertigo",
  "post_nasal_drip", "anosmia", "dysphonia", "salivary_gland_swelling",
  "eustachian_tube_dysfunction", "mastoiditis_concern", "laryngitis",
  "oral_ulcers", "tongue_swelling", "submandibular_swelling", "otorrhea",
  "otalgia_referred", "trismus", "nasal_polyps", "chronic_sinusitis_flare",
  // Pulmonary
  "cough", "shortness_of_breath", "wheezing", "asthma_exacerbation",
  "copd_exacerbation", "pneumonia", "bronchitis", "hemoptysis", "pleurisy",
  "hypoxia", "sleep_disordered_breathing", "pulmonary_embolism_concern",
  "pneumothorax_concern", "pleural_effusion", "respiratory_failure",
  "night_cough", "productive_cough", "post_covid_dyspnea",
  "bronchiectasis_flare", "interstitial_lung_flare", "laryngospasm",
  // Cardiac
  "chest_pain", "palpitations", "syncope", "atrial_fibrillation",
  "hypertensive_urgency", "decompensated_heart_failure", "leg_swelling", "bradycardia",
  "tachycardia", "chest_wall_pain", "cardiac_arrest_post", "endocarditis_concern",
  "aortic_stenosis_symptoms", "myocarditis_concern", "pericarditis", "svt",
  "sick_sinus_syndrome", "complete_heart_block_symptoms",
  // GI
  "abdominal_pain", "nausea_vomiting", "diarrhea", "constipation", "dysphagia",
  "jaundice", "gi_bleeding", "rectal_bleeding", "appendicitis_like",
  "cholecystitis_like", "pancreatitis_like", "bowel_obstruction", "gerd_esophageal",
  "ascites", "hepatitis_like", "mesenteric_ischemia_concern", "hernia_pain",
  "inflammatory_bowel_flare", "diverticulitis_like", "rectal_prolapse",
  "gastroparesis_symptoms", "small_bowel_obstruction", "toxic_megacolon_concern",
  "hepatic_encephalopathy_concern", "spontaneous_bacterial_peritonitis_concern",
  "esophageal_spasm", "mallory_weiss_concern", "ischemic_colitis_concern",
  // GU / Renal
  "uti", "hematuria", "flank_pain", "urinary_retention", "testicular_pain",
  "vaginal_bleeding", "pelvic_pain", "pelvic_pain_ovarian_torsion", "sti_exposure",
  "ectopic_pregnancy_concern", "urinary_incontinence", "prostatitis",
  "acute_kidney_injury", "nephrolithiasis", "epididymitis", "hydrocele",
  "vaginal_discharge", "scrotal_swelling", "renal_failure_symptoms",
  "urosepsis_concern", "interstitial_cystitis_flare", "fournier_gangrene_concern",
  "priapism", "phimosis_paraphimosis",
  // Neurology
  "headache", "headache_thunderclap", "dizziness", "weakness_numbness", "confusion",
  "seizure", "stroke_like", "vision_loss", "facial_droop", "tremor", "ataxia",
  "meningitis_concern", "diplopia", "neuropathy_symptoms", "encephalopathy_concern",
  "pseudotumor_cerebri", "bells_palsy", "trigeminal_neuralgia", "transient_global_amnesia",
  "cauda_equina_concern", "spinal_cord_compression", "migraine_aura",
  "parkinson_symptom_exacerbation", "ms_relapse", "guillain_barre_concern",
  "normal_pressure_hydrocephalus", "altered_consciousness",
  // MSK
  "back_pain", "joint_pain", "shoulder_pain", "knee_pain", "ankle_sprain",
  "neck_pain", "hip_pain", "fracture_dislocation", "gout_flare",
  "muscle_weakness", "compartment_syndrome_concern", "wrist_pain",
  "elbow_pain", "hand_pain", "foot_pain", "achilles_tendon_injury",
  "septic_arthritis_concern", "osteomyelitis_concern", "rhabdomyolysis_concern",
  "fibromyalgia_flare", "costochondritis", "trigger_finger",
  "lumbar_radiculopathy", "cervical_radiculopathy", "reactive_arthritis",
  "plantar_fasciitis", "rotator_cuff_injury", "avascular_necrosis_concern",
  // Dermatology
  "rash", "cellulitis", "abscess_skin", "urticaria", "shingles", "burns",
  "wound_infection", "laceration", "insect_bite_reaction", "pressure_ulcer",
  "contact_dermatitis", "eczema_flare", "psoriasis_flare", "petechia_purpura",
  "necrotizing_fasciitis_concern", "pilonidal_cyst", "paronychia",
  "drug_reaction_rash", "stevens_johnson_concern", "tinea_infection",
  "scabies", "impetigo", "folliculitis",
  // Psychiatric / Behavioral
  "anxiety", "depression", "suicidal_ideation", "agitation_psychosis", "panic_attack",
  "substance_intoxication", "withdrawal", "bipolar_episode", "ptsd_symptoms",
  "acute_stress_reaction", "eating_disorder_crisis", "self_harm",
  "acute_psychosis", "delirium", "catatonia_concern", "opioid_use_disorder",
  "alcohol_use_crisis", "medication_nonadherence_crisis",
  // Endocrine / Metabolic
  "hyperglycemia", "hypoglycemia", "thyroid_symptoms", "adrenal_crisis",
  "metabolic_derangement", "hypercalcemia", "hyponatremia", "hyperkalemia",
  "cushing_symptoms", "addisonian_crisis", "hyperthyroidism_crisis",
  "dka_concern", "hhs_concern", "myxedema_coma_concern", "pheochromocytoma_concern",
  // Infections / Systemic
  "fever", "flu_like", "sepsis_concern", "covid_like", "mononucleosis",
  "lyme_concern", "animal_bite", "hiv_concern", "tuberculosis_concern",
  "mrsa_infection", "influenza", "cellulitis_strep", "meningococcal_concern",
  "rabies_exposure", "tick_borne_illness", "fungal_infection",
  "parasitic_infection", "post_travel_illness", "endocarditis_septic_emboli",
  "salmonella_typhi_concern", "dengue_concern",
  // Trauma / Environmental
  "head_injury", "facial_trauma", "eye_pain", "eye_trauma", "pelvic_fracture",
  "penetrating_wound", "overdose_intoxication", "poisoning_exposure",
  "heat_illness", "hypothermia_cold_exposure", "allergic_reaction",
  "near_drowning", "electrical_injury", "blast_injury", "crush_injury",
  "chemical_exposure", "carbon_monoxide_exposure", "altitude_sickness",
  "radiation_exposure", "frostbite",
  // Ophthalmology
  "red_eye", "acute_glaucoma", "corneal_abrasion", "uveitis", "retinal_detachment_concern",
  "subconjunctival_hemorrhage", "periorbital_cellulitis", "chemical_eye_exposure",
  "visual_field_defect", "optic_neuritis", "central_retinal_artery_occlusion",
  "horner_syndrome_concern", "strabismus_new_onset",
  // OB / GYN
  "pregnancy_complication", "postpartum_complication", "hyperemesis_gravidarum",
  "preeclampsia_concern", "placenta_previa_concern", "preterm_labor_concern",
  "mastitis", "ovarian_cyst_rupture", "endometriosis_pain", "menorrhagia",
  "postpartum_depression", "breast_lump", "amenorrhea", "dysmenorrhea",
  "polycystic_ovary_symptoms", "fibroids_pain",
  // General / Systemic
  "fatigue", "generalized_weakness", "insomnia", "dental_pain",
  "foreign_body_ingestion", "cancer_related_symptom", "unintentional_weight_loss",
  "lymphadenopathy", "night_sweats", "chronic_pain_crisis",
  "failure_to_thrive_adult", "cachexia", "hyperhidrosis",
  "excessive_thirst_polyuria", "unexplained_bruising",
  // Vascular
  "deep_vein_thrombosis", "aortic_dissection_concern", "peripheral_arterial_disease",
  "limb_ischemia_acute", "variceal_bleeding_concern", "superior_vena_cava_syndrome",
  "ruptured_aaa_concern", "arteriovenous_fistula_complication", "phlebitis",
  // Pediatric
  "croup", "febrile_seizure", "kawasaki_concern", "intussusception_concern",
  "epiglottitis_concern", "rsv_bronchiolitis", "neonatal_jaundice",
  "pediatric_foreign_body", "failure_to_thrive", "child_abuse_concern",
  "pediatric_asthma_exacerbation", "pediatric_dka", "pyloric_stenosis_concern",
  "meconium_aspiration", "omphalitis",
  // Hematology / Oncology
  "bleeding_disorder", "sickle_cell_crisis", "neutropenic_fever",
  "oncologic_emergency", "tumor_lysis_syndrome", "anemia_symptomatic",
  "thrombocytopenia", "hemolysis_concern", "hyperviscosity_syndrome",
  "febrile_neutropenia", "superior_vena_cava_syndrome_malignant",
  // Toxicology
  "opioid_overdose", "benzodiazepine_overdose", "acetaminophen_overdose",
  "stimulant_toxicity", "anticholinergic_toxidrome", "organophosphate_exposure",
  "serotonin_syndrome_concern", "neuroleptic_malignant_syndrome_concern",
  "digoxin_toxicity", "lithium_toxicity", "beta_blocker_overdose",
  "tricyclic_antidepressant_overdose", "alcohol_poisoning",
].sort();

export const COMPLAINTS_SET = new Set(COMPLAINTS);
