export type WeeklyExecutiveEmailInput = {
  clinicId: string;
  recipientEmail: string;
  headline: string;
  summaryLines: string[];
};

export function buildWeeklyExecutiveEmail(input: WeeklyExecutiveEmailInput) {
  return {
    to: input.recipientEmail,
    subject: `Weekly Executive Summary | ${input.clinicId}`,
    body: [
      input.headline,
      "",
      ...input.summaryLines.map(line => `- ${line}`),
      "",
      "Generated by Auralyn Clinical Decision Support System.",
    ].join("\n"),
  };
}

export function getDemoEmailPreview(): WeeklyExecutiveEmailInput {
  return {
    clinicId: "clinicA",
    recipientEmail: "admin@clinicA.com",
    headline: "Clinic A processed 3,200 cases with healthy margin and stable safety posture.",
    summaryLines: [
      "Override rate: 11.0%",
      "Average satisfaction: 4.56",
      "Top pressure complaint: dizziness",
      "Safety mode: elevated",
      "Revenue margin: 41.2%",
      "Escalation rate: 8.0%",
    ],
  };
}
