/**
 * Moat Intelligence Aggregator
 *
 * Single API to retrieve the full defensibility picture:
 *   - Flywheel velocity
 *   - Rare case advantage
 *   - Network learning status
 *   - Clinic lock-in scores
 *   - Overall Moat Score (0-100)
 *
 * Surface this to investors, partners, and clinic administrators
 * to demonstrate compounding advantage.
 */

import { getFlywheelStats }   from "./flywheelEngine";
import { getRareCaseStats }    from "./rareCaseEngine";
import { getNetworkStats }     from "./networkLearning";
import { getAllClinicValues }   from "./clinicLockIn";
import { listGeneratedGoldenCases } from "../learning/goldenCaseAutoGenerator";

export interface MoatScorecard {
  overall:     number;       // 0-100 composite moat score
  grade:       "A" | "B" | "C" | "D" | "F";
  components: {
    flywheel:   number;      // 0-25
    rarity:     number;      // 0-25
    network:    number;      // 0-25
    lockin:     number;      // 0-25
  };
  flywheel: {
    totalEncounters:     number;
    validatedEncounters: number;
    goldenPromotions:    number;
    velocity24h:         number;
    velocity7d:          number;
    validationRate:      number;
  };
  rarity: {
    totalDiagnosesSeen: number;
    totalEncounters:    number;
    rareDxCount:        number;
    ultraRareDxCount:   number;
    rareCoverageRate:   number;
  };
  network: {
    activeClinicCount:   number;
    totalNetworkCases:   number;
    specialtyBreakdown:  Array<{ specialty: string; cases: number; share: number }>;
    networkMultiplier:   number;  // 1 + log(clinics)
  };
  lockin: {
    clinicsWithHighCost:     number;
    averageValueScore:       number;
    topClinicValueScore:     number;
    totalAccumulatedPatterns: number;
  };
  goldenDataset: {
    total:            number;
    autoGenerated:    number;
    specialtyCoverage: number;
  };
  generatedAt: string;
}

function scoreGrade(score: number): MoatScorecard["grade"] {
  if (score >= 80) return "A";
  if (score >= 65) return "B";
  if (score >= 50) return "C";
  if (score >= 35) return "D";
  return "F";
}

function cap25(n: number): number {
  return Math.min(25, Math.max(0, n));
}

export async function computeMoatScorecard(): Promise<MoatScorecard> {
  const [flyStats, rareStats, netStats, clinicValues, goldenCases] = await Promise.all([
    getFlywheelStats(),
    getRareCaseStats(),
    getNetworkStats(),
    getAllClinicValues(),
    listGeneratedGoldenCases().catch(() => [] as any[]),
  ]);

  /* ── flywheel score (0-25) ─────────────────────────────────────────────── */
  // 25 points at 10,000 validated encounters; linear below
  const flywheelScore = cap25(
    (flyStats.validatedEncounters / 10000) * 15 +
    (flyStats.velocity24h / 50)            * 5  +
    (flyStats.goldenPromotions / 500)      * 5
  );

  /* ── rarity score (0-25) ──────────────────────────────────────────────── */
  // 25 points at 50 unique rare diagnoses covered
  const rarityScore = cap25(
    (rareStats.rareDxCount / 50)      * 15 +
    (rareStats.ultraRareDxCount / 10) * 10
  );

  /* ── network score (0-25) ─────────────────────────────────────────────── */
  // 25 points at 20 active clinics + 10k network cases
  const networkScore = cap25(
    (netStats.activeClinicCount / 20)   * 15 +
    (netStats.totalNetworkCases / 10000) * 10
  );

  /* ── lock-in score (0-25) ─────────────────────────────────────────────── */
  const highCostClinics = clinicValues.filter(c => c.switchingCostLabel === "HIGH" || c.switchingCostLabel === "VERY_HIGH");
  const avgValue = clinicValues.length
    ? clinicValues.reduce((s, c) => s + c.valueScore, 0) / clinicValues.length
    : 0;
  const lockInScore = cap25(
    (highCostClinics.length / 5)   * 15 +
    (avgValue / 2000)              * 10
  );

  const overall = Math.round(flywheelScore + rarityScore + networkScore + lockInScore);

  /* ── golden dataset ───────────────────────────────────────────────────── */
  const goldenArr = Array.isArray(goldenCases) ? goldenCases : [];
  const specialtyCoverage = new Set(goldenArr.map((c: any) => c.specialty ?? c.complaint ?? "general")).size;

  return {
    overall,
    grade: scoreGrade(overall),
    components: {
      flywheel: Math.round(flywheelScore),
      rarity:   Math.round(rarityScore),
      network:  Math.round(networkScore),
      lockin:   Math.round(lockInScore),
    },
    flywheel: {
      ...flyStats,
      validationRate: flyStats.totalEncounters > 0
        ? flyStats.validatedEncounters / flyStats.totalEncounters
        : 0,
    },
    rarity: {
      ...rareStats,
      rareCoverageRate: rareStats.totalDiagnosesSeen > 0
        ? rareStats.rareDxCount / rareStats.totalDiagnosesSeen
        : 0,
    },
    network: {
      ...netStats,
      networkMultiplier: netStats.activeClinicCount > 1
        ? 1 + Math.log(netStats.activeClinicCount)
        : 1,
    },
    lockin: {
      clinicsWithHighCost:      highCostClinics.length,
      averageValueScore:        Math.round(avgValue),
      topClinicValueScore:      clinicValues[0]?.valueScore ?? 0,
      totalAccumulatedPatterns: clinicValues.reduce((s, c) => s + c.uniqueDiagnoses, 0),
    },
    goldenDataset: {
      total:            goldenArr.length,
      autoGenerated:    goldenArr.filter((c: any) => c.id?.startsWith("AUTO_")).length,
      specialtyCoverage,
    },
    generatedAt: new Date().toISOString(),
  };
}
